### ISSUE TITLE
Cant find/rename AppleACPIPS2Nub.kext and AppleACPIPS2Nub.bak

### ISSUE THREAD

**Issue by MTechDE** [wmchris/DellXPS15-9550-OSX#10]
I want to rename the files just like you wrote in the tutorial
```

sudo cp -r ./Post-Install/LE-Kexts/* /Library/Extensions/  
sudo mv /System/Library/Extensions/AppleACPIPS2Nub.kext /System/Library/Extensions/AppleACPIPS2Nub.bak  
sudo mv /System/Library/Extensions/ApplePS2Controller.kext /System/Library/Extensions/ApplePS2Controller.bak 
sudo ./AD-Kexts/VoodooPS2Daemon/_install.command
```

But the terminal says that these files don't exist. I went to the Libary/Extension folder and also can't find theses two files

**Comment by wmchris** [comment]
just ignore it then. :-)

**Comment by wmchris** [comment]
updated tutorial. some machines just dont have these files (depends on fresh installation, upgrade, etc.)
new commands in https://github.com/wmchris/DellXPS15-9550-OSX/commit/90bb2b08679190808b9a897e71719e54a435ef94

**Comment by MTechDE** [comment]
Thank you :)
