### ISSUE TITLE
do we need to remove any patches or kext if using native power management? 

### ISSUE THREAD

**Issue by carlosxfigueroa** [wmchris/DellXPS15-9550-OSX#100]
as title says

**Comment by krim404** [comment]
yes.

**Comment by carlosxfigueroa** [comment]
which ones would i have to remove? if you dont mind helping

**Comment by carlosxfigueroa** [comment]
any help is appreciated

**Comment by carlosxfigueroa** [comment]
also i know i didnt state this in my issue but netflix doesnt work with safari ive seen it could be related to drm and have tried a couple fixes but nothing works so far

**Comment by krim404** [comment]
its written in the repository...
