### ISSUE TITLE
HINT: Keyboard Type reset (for swapped ~, < or ^ keys)

### ISSUE THREAD

**Issue by ppeetteerrs** [wmchris/DellXPS15-9550-OSX#101]
Just FYI, in order to use the backtick and tilde properly, keyboard type should be ISO when it was being setup. Thanks!

**Comment by krim404** [comment]
depends on the keyboard and the location ;-)

however, you can easily delete the file `/Library/Preferences/com.apple.keyboardtype.plist`, followed by a reboot to re-set the keyboard type (in case "Change Keyboard Type" is not visible in "System Preferences/Keyboard")
