### ISSUE TITLE
Monitor won't wake up from sleep when connect to hdmi

### ISSUE THREAD

**Issue by carlosxfigueroa** [wmchris/DellXPS15-9550-OSX#102]
As title says, can't wake up the monitor when put to sleep with the lid closed but if I unplug and open the lid it works

**Comment by krim404** [comment]
an external monitor? how connected? vga? which adapter used?

**Comment by carlosxfigueroa** [comment]
Connected with HDMI through the actual port no adapter

**Comment by carlosxfigueroa** [comment]
Yes external Samsung monitor

**Comment by krim404** [comment]
cannot confirm, works well on my machine
