### ISSUE TITLE
SATA-100-series-unsupported should be removed

### ISSUE THREAD

**Issue by mpco** [wmchris/DellXPS15-9550-OSX#103]
In my opinion, SATA-100-series-unsupported and SSDT-SATA have the same function. I found SATA-100-series-unsupported not loaded by using `kextstat | grep -i sata`

**Comment by krim404** [comment]
it's in there in case someone has the XPS with sata instead the nvme drive. Never seen them in the wild. Do you have one with SATA connected? if yes, can you confirm, that the SSDT patch is enough?

**Comment by mpco** [comment]
Sorry, my XPS don't have SATA. Just keep kext there. Anyway, there is no bad consequences.
