### ISSUE TITLE
Pre-conditions of upgrading to 10.14.4?

### ISSUE THREAD

**Issue by exactmultiple3425** [wmchris/DellXPS15-9550-OSX#104]
I tried to upgrade to 10.14.4 but ends up getting kernel panic, luckily I can still boot back to the original 10.14.3 install, are there any steps for me to do before upgrading? Thanks.

My machine is i5 w/ 1080p screen

**Comment by krim404** [comment]
Clover version r4895, AppleALC 1.3.6, Lilu 1.3.5 and WhateverGreen 1.2.7

**Comment by exactmultiple3425** [comment]
I see, so I have to upgrade AppleALC 1.3.6, Lilu 1.3.5 and WhateverGreen 1.2.7 too

**Comment by krim404** [comment]
if you have a working enviroment, i would love to get a pull request on this repository with the updated versions. i'm unable to test it myself at the moment. :-(

**Comment by exactmultiple3425** [comment]
I see, I will try to get the environment working after upgrade first,
thanks.

wmchris <notifications@github.com> 於 2019年3月27日 週三 18:50 寫道：

**Comment by exactmultiple3425** [comment]
I had created a PR #105

**Comment by krim404** [comment]
merged. also updated clover.
