### ISSUE TITLE
10.15 Error Reporting for New Installation

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#106]
![O%X8@U0I$YGRGSA {8(L{0D](https://user-images.githubusercontent.com/25170955/59085800-5b9e9380-8932-11e9-9fd3-d5e7a07448d9.jpg)

**Comment by ghsssss** [comment]
if delete SMCLightSensor, the error is IOconsoleusers:gio sreenkicjstate3,hs 0,hs0,now0,sm 0x0

**Comment by krim404** [comment]
thank you for your test, but the screenshot is cropped at the most important part.

**Comment by golimpio** [comment]
@yaozaiyu Do you still have this issue? The latest VirtualSMC kexts are working now, try to use the ones from the 10.15 branch.

**Comment by ghsssss** [comment]
@golimpio 没有这个问题了
