### ISSUE TITLE
Sleep results in reboot

### ISSUE THREAD

**Issue by General13K7** [wmchris/DellXPS15-9550-OSX#107]
I have 10.14.4. I do not touch any kexts, do not touch system settings, clover settings and etc, but in one day i have no sleep... it fails in reboot. Tried to sudo pmset -a hibernatemode 0 && sudo reboot - nothing changed. 
tried 
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0

nothing changed.

I have windows on another partition. can it break my sleep?
what can i do to repair it?

**Comment by krim404** [comment]
would you mind reading the tutorial first, before asking questions?
https://github.com/wmchris/DellXPS15-9550-OSX/tree/10.14/10.14/Post-Install/Additional%20Steps/Hibernation
