### ISSUE TITLE
10.14.5 can't go to sleep

### ISSUE THREAD

**Issue by lamhoangtung** [wmchris/DellXPS15-9550-OSX#108]
I tried to upgrade from `10.14.3` to `10.14.5` yesterday and the whole thing broke, I only managed to boot by a fake platform-id

After spending some time fixing the problem, I decided to do a clean install, then patch Intel Framebuffer, then upgrade to `10.14.5`. Since then everything is working fine except for the **SLEEP** feature

Whenever I hit Sleep button or close the lid, the screen go off, the music stop ... but when I open the lid or touch anything, the machine just resume to the last states without even asking me to type in any password. Looks like the machine is not sleeping at all.

The sleep works fine back in `10.14.3`.

I tried to turn off some network wake up, power nap setting. Also tried all of your script in this repo 👍 

Here is my `pmset -g assertions` log:
```bash
Hoangs-MacBook-Pro:Hibernation linus$ pmset -g assertions
2019-06-21 11:04:45 +0700 
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   PreventSystemSleep             0
   ExternalMedia                  0
   PreventUserIdleSystemSleep     0
   NetworkClientActive            0
Listed by owning process:
   pid 94(hidd): [0x000003500009810c] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle.4294968193.3" 
	Timeout  will fire in 600 secs Action=TimeoutActionRelease
Kernel Assertions: 0x4=USB
   id=501  level=255 0x4=USB mod=1/1/70, 8:00 AM description=com.apple.usb.externaldevice.14300000 owner=BCM920703 Bluetooth 4.1
   id=502  level=255 0x4=USB mod=1/1/70, 8:00 AM description=com.apple.usb.externaldevice.14200000 owner=USB Receiver
Idle sleep preventers: IODisplayWrangler
```
Also tried to quit all app before sleep (since they can prevent Mac from sleeping) but the same problem still persist 

Do you have any idea what could go wrong and how can I solve the problem. Thanks a lot ;)

**Comment by krim404** [comment]
cannot confirm, upgrade works fine if you update the clover folder as well.
the system will never go to hibernation, what you're calling "sleep". Sleep is indeed: stop fans, disable monitor, halt all tasks and reduce power consumption.
Ofc all timers will continue. If you have never set up a timer for automatic logout or asking for a password after xx minutes idle, then it will not appear there either.

You can try to make hibernation run on your machine - but it has been unstable in the past with the posibility for a complete storage failure and loss of all data. 

so not a bug, normal behaviour.

**Comment by lamhoangtung** [comment]
The problem is gone after a fews reboot ???
Thank you @wmchris for your help <3
