### ISSUE TITLE
Only 31MB VRAM

### ISSUE THREAD

**Issue by MTechDE** [wmchris/DellXPS15-9550-OSX#11]
I just noticed that the "Mac" have access to only 31MB VRAM

**Comment by wmchris** [comment]
then something with the minstolensize patch went wrong.

**Comment by MTechDE** [comment]
So should i generate a new ID with Clover Configurator?
And should i also change the SMBISO to MacBook Pro 15?

**Comment by wmchris** [comment]
this has nothing to do with it.  

basierend auf deinem Namen und dem Ort gehe ich von aus wir können deutsch schreiben ;-)
hast du die config.plist aus dem Post-Install Ordner korrekt kopiert? Erst diese schaltet die Grafikfunktionalität für OSX frei.

**Comment by MTechDE** [comment]
Gerne :)

Ich habe gerade bemerkt, dass ich anstelle der config.plist aus dem Post-InstallOrdner, die aus dem 10.12/Clover Ordner verwendet habe.
Ich installiere eben das System neu und gebe gleich bescheid, ob dann alles Funktioniert hat

**Comment by wmchris** [comment]
muss nichts neu installiert werden. Einfach austauschen.

**Comment by MTechDE** [comment]
Nach dem Austausch bekomme ich leider keinen Start mehr hin.
Folgender Fehler wird beim Booten angegeben:
`fTimerServicerMatching timed out, fNotifications 0`

**Comment by wmchris** [comment]
ich vermute, dass sämtliche "post-installation" vorgänge nicht korrekt umgesetzt wurden.
Der angezeigte Fehler ist vermutlich nicht der wirkliche Fehler. 

Mit der config.plist werden nur zwei Sachen geändert:
1. intel GPU aktiviert
2. hackrnvme deaktiviert (die kext muss bis dahin irgendwie geladen sein)

wenn der PC dann nicht mehr bootet kann dies auch nur zwei Gründe haben:
1. 4k Monitor, aber kein 4k Fix eingespielt (./10.12/Post-Install/AD-Kexts/UHD-Kexts)
2. HackrNVMe nicht installiert (./10.12/Post-Install/AD-Kexts/HackrNVMe)

**Comment by MTechDE** [comment]
Ist die Geschichte mit den HackrNVMe Kext Dateien nicht so, dass diese nur eingespielt werden müssen, bei der Umstellung auf 4k Blöcke der SSD?
Und die 4k Patches sollte doch eigentlich mit diesem Befehl installiert sein:

`sudo cp ./Post-Install/AD-Kexts/UHD-Kexts/* /EFI/EFI/CLOVER/kexts/10.12/`

**Comment by wmchris** [comment]
umgedreht. diese müssen eingespielt werden, wenn man NICHT auf 4k wechselt.

**Comment by MTechDE** [comment]
Okay danke. Dann werde ich mal die Samsung NVME M2 SSD auf die 4k Blockgröße umstellen

**Comment by wmchris** [comment]
bitte um feedback, ob die samsung 4k untersützt. die teureren evo sind nämlich nicht 4k kompatibel.

**Comment by MTechDE** [comment]
Ja leider ist sie nicht kompatibel.
