### ISSUE TITLE
low brightness compared to windows

### ISSUE THREAD

**Issue by tiger511** [wmchris/DellXPS15-9550-OSX#111]
I used your repo to install Mac on my XPS 15 9550 (4K Sharp IGZO Display,i3-6100H,512 GB PM951 Samsung SSD).Everything works fine so far except the display brightness is lower compared to Windows.I used full brightness of hackintosh and Windows 10.Windows seems more brighter at full brightness.I think mac is not been able to utilize full range brightness this display has to offer.

**Comment by krim404** [comment]
i cannot confirm this. same display here, brightness is the same. please investigate your issue further. sadly i cannot help with issues i cannot replicate.

**Comment by krim404** [comment]
no update in over 10 days, so i close this.
