### ISSUE TITLE
Extreme battery drain. Even in standby

### ISSUE THREAD

**Issue by gianlucanotaro** [wmchris/DellXPS15-9550-OSX#112]
The fans on my machine keep spinning on maximum, no matter what i am doing. Even on standby. Battery is drained from 100 to 0 in approx 2.5hours.

Any fixes?

**Comment by krim404** [comment]
your machine is not on standby if the fans are spinning.
try disabling the sd card reader in bios.

**Comment by gianlucanotaro** [comment]
i look it up in the bios and it was already disabled. Any other solutions?

**Comment by krim404** [comment]
this was not an intended solution. just a minor tweak to add a few minutes to your battery timespan.

Your computer is obviously not getting into standby. this can have multiple reasons - but none has to do with something from this repository. standby works out of the box.

format your hdd and redo the tutorial step by step. test it without installing any 3rd party applications. check if something is preventing sleep by using the pmset tool. 

if it still not working then there must be something broken on your machine.

**Comment by tiger511** [comment]
Try removing SSDT-DeepIdle.aml from patched folder.i dont think we need it in our machines? @wmchris  can you shed some info on this.

**Comment by krim404** [comment]
afaik this is required, but never tried what happens w/o it.

**Comment by tiger511** [comment]
Everything works fine without this aml.We should not using not working patches.Less is better,right?

**Comment by achaheen** [comment]
Hi, I have disabled the SD card reader and I still have a battery drain at 1.5-2% for each 1 hour, is this a normal discharging rate for sleeping ?

**Comment by fttx** [comment]
> Hi, I have disabled the SD card reader and I still have a battery drain at 1.5-2% for each 1 hour, is this a normal discharging rate for sleeping ?

I've the same issue, people are getting ~2% battery loss for 10 hours with the XPS 9560.

**Comment by krim404** [comment]
maybe this is fixed, too with #122 ?

**Comment by fttx** [comment]
I've tested it this night and it went from 99% to 94% in about 9 hours. Perhaps it's due to the fact that the battery discharge rate is not linear?

**Comment by krim404** [comment]
well 1% in 2h seems fine and is very plausible with other computer systems. 
i would say it's fixed.

btw the 2% in 10h on the 9560 is absolute bulls***.

**Comment by clemdep88** [comment]
gianlucanotaro, I also have a problem with my battery life. Battery is drained from 100 to 0 in approx 2.5hours. I tried a re-install and that change nothing, do you find a solution?

**Comment by krim404** [comment]
i'll close this ticket as it has been fixed in https://github.com/wmchris/DellXPS15-9550-OSX/commit/c28205eb04a2156bccc329f7d40ff587ab7df19a
