### ISSUE TITLE
键盘无法打出波浪号和逗点

### ISSUE THREAD

**Issue by Beipy** [wmchris/DellXPS15-9550-OSX#113]
键盘无法打出波浪号和逗点
![QQ20190730-0](https://user-images.githubusercontent.com/33574750/62178244-efad3a00-b37a-11e9-84c3-b0ffa01f37e9.jpg)

**Comment by tiger511** [comment]
Go System Preferences>Keyboard>Change keyboard type and select "ISO".i've attached screenshot below 

<img width="1038" alt="Screenshot 2019-07-31 at 1 01 49 PM" src="https://user-images.githubusercontent.com/53279423/62190751-f005ff00-b393-11e9-9e5c-9848d3c1fe0d.png">

**Comment by krim404** [comment]
english!
