### ISSUE TITLE
IONVMeFamily Crashing randomly while using browser

### ISSUE THREAD

**Issue by tiger511** [wmchris/DellXPS15-9550-OSX#114]
I'm getting random Fatal Error CSTS=0x1  from NVMe Controller.I've attached crash report.My SSD is Samsung PM951 using apfs File system.

Anonymous UUID:       811DEF89-82C2-9924-ECDC-06F256C571E1

Wed Jul 31 12:57:41 2019

*** Panic Report ***
panic(cpu 0 caller 0xffffff7f8e773b30): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x342 VID/DID=0xa802144d
. FW Revision=BXV76D0Q\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-387.270.1/IONVMeController.cpp:5334
Backtrace (CPU 0), Frame : Return Address
0xffffff81ff78ba10 : 0xffffff800b5ad6ed 
0xffffff81ff78ba60 : 0xffffff800b6e9185 
0xffffff81ff78baa0 : 0xffffff800b6da8ba 
0xffffff81ff78bb10 : 0xffffff800b55ab40 
0xffffff81ff78bb30 : 0xffffff800b5ad107 
0xffffff81ff78bc50 : 0xffffff800b5acf53 
0xffffff81ff78bcc0 : 0xffffff7f8e773b30 
0xffffff81ff78be20 : 0xffffff800bc5e047 
0xffffff81ff78be90 : 0xffffff800bc5df69 
0xffffff81ff78bec0 : 0xffffff800b5ec885 
0xffffff81ff78bf40 : 0xffffff800b5ec425 
0xffffff81ff78bfa0 : 0xffffff800b55a0ce 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[A67B3600-6FE3-3037-AC41-8C2D353B6250]@0xffffff7f8e766000->0xffffff7f8e7a5fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[888F591F-8A21-30F9-812F-D366292AA679]@0xffffff7f8c399000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[202F4F5C-5E3C-35A9-A7AD-F85B0E3CD199]@0xffffff7f8be95000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[B83F29B8-24AC-303B-BBBA-CF332168FDE6]@0xffffff7f8c56f000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[71BB22B0-3075-35A1-B04E-FBAC574DA80D]@0xffffff7f8c18f000
            dependency: com.apple.iokit.IOReportFamily(47)[0BC9F93B-456A-3D97-BE4C-69DCBB5E8A3C]@0xffffff7f8c9fc000

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 nv_disable=1 agdpmod=vit9696 -v brcmfx-country=#a darkwake=no -lilubetaall kext-dev-mode=1 

Mac OS version:
18G84

Kernel version:
Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Kernel UUID: 982F17B3-0252-37FB-9869-88B3B1C77335
Kernel slide:     0x000000000b200000
Kernel text base: 0xffffff800b400000
__HIB  text base: 0xffffff800b300000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

System uptime in nanoseconds: 688962769788
last loaded kext at 137257997690: com.apple.filesystems.smbfs	3.3.2 (addr 0xffffff7f8e0de000, size 442368)
last unloaded kext at 527316000029: ru.usrsse2.SMCLightSensor	1 (addr 0xffffff7f8ed21000, size 16384)
loaded kexts:
com.XPS.VerbStub	1.0.3
com.intel.driver.EnergyDriver	3.5.5
com.alexandred.VoodooI2CHID	1
org.rehabman.voodoo.driver.PS2Keyboard	1.9.2
org.rehabman.driver.FakePCIID	1.3.15
ru.joedm.SMCSuperIO	1.0.6
com.alexandred.VoodooI2C	2.1.6
org.rehabman.voodoo.driver.PS2Controller	1.9.2
org.coolstar.VoodooGPIO	1.1
as.vit9696.SMCProcessor	1.0.6
as.vit9696.AppleALC	1.3.9
xyz.racermaster.NoTouchID	1.0.2
org.tw.CodecCommander	2.7.1
as.lvs1974.AirportBrcmFixup	2.0.2
as.vit9696.WhateverGreen	1.3.0
ru.usrsse2.SMCBatteryManager	1
ru.usrsse2.SMCLightSensor	1
as.vit9696.VirtualSMC	1.0.6
as.vit9696.Lilu	1.3.7
com.alexandred.VoodooI2CServices	1
com.apple.filesystems.smbfs	3.3.2
com.apple.filesystems.msdosfs	1.10
com.apple.driver.AudioAUUC	1.70
com.apple.fileutil	20.036.15
com.apple.filesystems.autofs	3.0
com.apple.filesystems.ntfs	3.13
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AGPM	110.25.11
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AppleHDA	282.54
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleMCCSControl	1.5.9
com.apple.AGDCPluginDisplayMetrics	3.50.12
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.14d3
com.apple.private.KextAudit	1.0
com.apple.driver.eficheck	1
com.apple.driver.pmtelemetry	1
com.apple.driver.AppleOSXWatchdog	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleIntelSKLGraphics	12.1.0
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleIntelSKLGraphicsFramebuffer	12.1.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleTopCaseHIDEventDriver	138.4
com.apple.driver.AppleVirtIO	2.1.3
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.filesystems.apfs	945.275.7
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleAHCIPort	329.260.5
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleBacklight	170.12.12
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	201
com.apple.security.TMSafetyNet	8
com.apple.iokit.IOAVBFamily	760.6
com.apple.plugin.IOgPTPPlugin	740.2
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	282.54
com.apple.kext.OSvKernDSPLib	528
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.AppleSSE	1.0
com.apple.AppleGPUWrangler	3.50.12
com.apple.AppleGraphicsDeviceControl	3.50.12
com.apple.iokit.IOAcceleratorFamily2	404.14
com.apple.iokit.IOSurface	255.6.1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleHDAController	282.54
com.apple.iokit.IOHDAFamily	282.54
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleActuatorDriver	2450.1
com.apple.driver.AppleHSBluetoothDriver	138.4
com.apple.driver.IOBluetoothHIDDriver	6.0.14d3
com.apple.iokit.IOBluetoothFamily	6.0.14d3
com.apple.driver.AppleMultitouchDriver	2450.1
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.iokit.IOSerialFamily	11
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleUSBMergeNub	900.4.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleEFINVRAM	2.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOGraphicsFamily	530.66
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.260.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro13,3, BootROM 259.0.0.0.0, 2 processors, Intel Core i3, 2.71 GHz, 16 GB, SMC 2.38f7
Graphics: kHW_IntelHDGraphics530Item, Intel HD Graphics 530, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR4, 2133 MHz, SK Hynix, HMA41GS6AFR8N-TF
Memory Module: BANK 1/DIMM0, 8 GB, DDR4, 2133 MHz, SK Hynix, HMA41GS6AFR8N-TF
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x24), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
PCI Card: Intel 10 Series Chipset Family USB xHCI Host Controller, USB Controller, Built In
USB Device: USB 3.0 Bus
Thunderbolt Bus:

**Comment by krim404** [comment]
check for hardware errors.

**Comment by tiger511** [comment]
Hardware is fine since it doesn't happen with windows.This KP is quite random.Not usually related to browser.

**Comment by krim404** [comment]
i had multiple people with such failures which "worked in windows". till the defect was so severe it destroyed windows as well. 

so before debugging it further, do a complete hardware checkup from a linux boot disk.

**Comment by krim404** [comment]
no updates, so i'll close it.

**Comment by TiberioG** [comment]
I'm having the same random issue, just happened after waking up from sleep.
Any suggestion for a linux hardware checkup?
Thanks in advance 

` *** Panic Report ***
panic(cpu 2 caller 0xffffff7f8c3efc0c): nvme: "Fatal error occurred. CSTS=0x0 US[1]=0x0 US[0]=0x1d4 VID/DID=0x10f1179
. FW Revision=57DA4105\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-387.260.15/IONVMeController.cpp:5334
Backtrace (CPU 2), Frame : Return Address
0xffffff92232d3a70 : 0xffffff80091aea2d 
0xffffff92232d3ac0 : 0xffffff80092e9e95 
0xffffff92232d3b00 : 0xffffff80092db70a 
0xffffff92232d3b70 : 0xffffff800915bb40 
0xffffff92232d3b90 : 0xffffff80091ae447 
0xffffff92232d3cb0 : 0xffffff80091ae293 
0xffffff92232d3d20 : 0xffffff7f8c3efc0c 
0xffffff92232d3e80 : 0xffffff7f8c3efad6 
0xffffff92232d3ec0 : 0xffffff80091ed9b5 
0xffffff92232d3f40 : 0xffffff80091ed555 
0xffffff92232d3fa0 : 0xffffff800915b0ce 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[FAFF8EA6-B8EF-314D-886A-DEAB39FF3EA9]@0xffffff7f8c3e2000->0xffffff7f8c421fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[A367CF6B-B3EA-36FE-86E6-03B771CA8A69]@0xffffff7f8a142000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[CC6A465F-5A24-304D-B9DF-8C27819CC214]@0xffffff7f89a95000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[C3C74D36-E06B-3753-A373-5BC9D486DD9C]@0xffffff7f8a27a000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[D43332F2-2D40-3DF1-8F77-D633BCDAE660]@0xffffff7f89dd6000
            dependency: com.apple.iokit.IOReportFamily(47)[5772C11C-ED28-322A-910F-874583B23101]@0xffffff7f8a707000
BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 nv_disable=1 agdpmod=vit9696 brcmfx-country=#a darkwake=no -lilubetaall kext-dev-mode=1 
Mac OS version:
18F132 
Kernel version:
Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
Kernel UUID: 7C8BB636-E593-3CE4-8528-9BD24A688851
Kernel slide:     0x0000000008e00000
Kernel text base: 0xffffff8009000000
__HIB  text base: 0xffffff8008f00000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)
System uptime in nanoseconds: 56790900742519
last loaded kext at 11897398059818: com.apple.filesystems.exfat	1.4 (addr 0xffffff7f8ceef000, size 65536)
loaded kexts:`

**Comment by phaberest** [comment]
Just got the same error. After a quick search it looks like https://github.com/acidanthera/NVMeFix might fix the issue, I'm going to run a test from the BIOS to see if there's anything wrong with my Samsung NVME and will try to use the fix to see if it works

--- EDIT

Just checked for bad sectors under linux and there´s nothing wrong with it
```
~                                                                                                                                                                                                          
▶ sudo badblocks -v /dev/nvme0n1 > badsectors.txt
[sudo] password for phaberest: 
Checking blocks 0 to 500107607
Checking for bad blocks (read-only test): 
done                                                 
Pass completed, 0 bad blocks found. (0/0/0 errors)
```

The BIOS diagnostic tool is only complaining about the battery, but that´s something I know and is completely unrelated

Using nvme-cli it also does not report anything to worry about
```
~/nvme-cli  master ✔                                                                                                                                                                              228d ◒  ⍉
▶ sudo nvme smart-log /dev/nvme0n1
Smart Log for NVME device:nvme0n1 namespace-id:ffffffff
critical_warning                        : 0
temperature                             : 38 C
available_spare                         : 100%
available_spare_threshold               : 50%
percentage_used                         : 6%
endurance group critical warning summary: 0
data_units_read                         : 80,082,599
data_units_written                      : 80,681,290
host_read_commands                      : 1,827,762,046
host_write_commands                     : 1,304,174,045
controller_busy_time                    : 5,859
power_cycles                            : 9,636
power_on_hours                          : 11,057
unsafe_shutdowns                        : 549
media_errors                            : 0
num_err_log_entries                     : 631
Warning Temperature Time                : 0
Critical Composite Temperature Time     : 0
Thermal Management T1 Trans Count       : 0
Thermal Management T2 Trans Count       : 0
Thermal Management T1 Total Time        : 0
Thermal Management T2 Total Time        : 0
```
