### ISSUE TITLE
Why FileVault 2 isn't working ?

### ISSUE THREAD

**Issue by jief666** [wmchris/DellXPS15-9550-OSX#116]
Do you have an idea of the problem ?
Thanks.

**Comment by golimpio** [comment]
I haven't enabled it, but check in the forum, someone have reported that it worked.

**Comment by krim404** [comment]
any update?

**Comment by jief666** [comment]
I don't have the XPS 15 yet, so can't tell...

**Comment by krim404** [comment]
so, this was not a bug report but just a question? then i close it.

**Comment by lamhoangtung** [comment]
I noticed that the README of BigSur tutorial no longer state FileVault 2 in the not working stuff ... Is this actually true ? @golimpio @wmchris

**Comment by golimpio** [comment]
> I noticed that the README of BigSur tutorial no longer state FileVault 2 in the not working stuff ... Is this actually true ? @golimpio @wmchris

I haven't tested FileVault myself, so I don't know if it's working or not. I've seem people reporting that it was working for Catalina, but I'm not sure about Big Sur.

**Comment by golimpio** [comment]
BTW, have anyone tried the steps for enabling FileVault in the Dortania guide?
- [https://dortania.github.io/OpenCore-Post-Install/universal/security/filevault.html](https://dortania.github.io/OpenCore-Post-Install/universal/security/filevault.html)

**Comment by krim404** [comment]
it is working. using it right now

**Comment by lamhoangtung** [comment]
Thanks for the confirmation
