### ISSUE TITLE
Does anyone replaced killer wireless with other card?

### ISSUE THREAD

**Issue by achaheen** [wmchris/DellXPS15-9550-OSX#117]
Hi,
I have obtained new wifi card BROADCOM  DW1820A and fixed it. Then I tried to run wifi but it start for 1 minute then turn off again. After that the system panic. Does anyone have a solution if faced the same issue or Is there any other suggestions for a different card?

**Comment by achaheen** [comment]
Never use this card DW1820A it causes the laptop to freeze after 10 minutes and it takes like 3 or 4 restarts to recover the system again. I have requested a different card DW1830 and waiting for it to arrive to test it.

**Comment by krim404** [comment]
in the tutorial i'll mention the DW1830 as replacement. It is the only trustworthy alternative which is known to work with the dell xps 9550 as well as osx.

**Comment by wannadream** [comment]
I am using DW1707 as replacement, works well with AR9565 kext fix. However, traffic is a little throttled. It does not affect daily work.
