### ISSUE TITLE
Error: couldn't allocate runtime area with high resolution clover theme

### ISSUE THREAD

**Issue by General13K7** [wmchris/DellXPS15-9550-OSX#118]
Hello. Today I decided to add the theme to the Clover. I chose Catalina4k theme. After I've installed it and do reboot, I received this error. I've already have slide=80 and Aptiofix installed. I've tried another slide numbers, nothing changed. After I delete Catalina4k theme and returned to BGM with slide=80, 10.15 normally booted. I think we do no need to install such big and massive themes. 

Maybe you can add this warning to your guide?

**Comment by General13K7** [comment]
Catalina4k is very good theme for 4k monitors and resolutions (i use it with my iMac based on Asrock and intel UHD630) but it's very big and with aptio bugs it may have this errors

**Comment by krim404** [comment]
hm. this is too specific for the tutorial, because adding modified themes to clover was never part of the tutorial. i'll change the issue title and close it, so maybe someone with the same issue will find it.
