### ISSUE TITLE
How can I type `````` 

### ISSUE THREAD

**Issue by sven97** [wmchris/DellXPS15-9550-OSX#119]
Thx for your wonderful job, the system runs on my machine perfectly!

But I do have a little issue when trying to type the \`\`\` sign through the keyboard (the key below Esc), which always gives §§§ instead of \`\`\`.

I tried the CapsLock, Shift, command, option ... almost everything but none of them work. 
I also tried different input sources such as default ABC, U.S. ... also not working.

Could you please give me a hint of how can I do that directly through the keyboard.

**Comment by ghost** [comment]
Did you read and follow the instructions on issue #99 ?

**Comment by sven97** [comment]
Thanks so so so much for your reference!
Changing the keyboard type to ISO fix the problem entirely. All the keys work perfectly using ISO!
Here is a quick note on how I solve this problem

System Preference -> Keyboard -> Change Keyboard Type... -> Changing auto-detected ANSI mode to ISO mode
