### ISSUE TITLE
HDMI Video/Audio - Macbook Pro 13,3

### ISSUE THREAD

**Issue by HeavenVolkoff** [wmchris/DellXPS15-9550-OSX#12]
I am currently using the MacBook Pro 13,3 SMBIOS on Sierra (12.4) and was able to enable HDMI Audio and Video with the following steps:

To enable video I added my boad-id `Mac-A5C67F76ED83108C` to `/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist` with attributed `none`.

To enable audio I added the `FakePCIID_Intel_HDMI_Audio.kext`, from RehabMan's `OS-X-Fake-PCI-ID` repo, to Clovers's Kext folder.

I am using this setup for a week now, and didn't have any bugs. So I think it could be a good addition to the tutorial.

**Comment by wmchris** [comment]
i add it to the newly created "fixes, additions" section. normally i said i will not support changes like these (i still suggest using iMac7,1 smbios) but well if it helps people... ;-)

**Comment by Piping** [comment]
@HeavenVolkoff Hi, I am wonder what HDA kext you are using to enable HDMI audio output?
1. VoodooHDA?
2. aDummyHDA + Codec
3. Modified AppleHDA

did you turn off or enable the AppleHDA patch in the config file?

did you turn remove the SSDT-ALC298.aml file in /EFI/Clover/ACPI/patched?

**Comment by HeavenVolkoff** [comment]
Hi @Piping,
Regarding audio, I am using pretty much this repo's vanilla setup:
> aDummyHDA + AppleHDA patches + SSDT-ALC298.aml

Enabling HDMI audio was as simple as adding `FakePCIID_Intel_HDMI_Audio.kext` to `/EFI/EFI/CLOVER/kexts`

However, as pointed by RehabMan in FakePCIID repo, for `FakePCIID_Intel_HDMI_Audio.kext` to work, `config.plist` must have been correctly set up:
>This kext won't fix other problems/mistakes you may have with your HDMI/DP setup (eg. missing "hda-gfx", mismatched "layout-id" injection, incorrect or wrong framebuffer patches, or missing ACPI renames).

I am running a slightly modified `config.plist`. However I don't remember modifying anything related to audio or graphics card from the one provided in this repo.

**Comment by Piping** [comment]
@HeavenVolkoff  Thank you very much for your detailed reply.

The aDummyHDA+AppleHDA patches + SSDT-ALC298 combination just dont give me speaker audio at all. So I use VoodooHDA instead.

However, I will try it again.

**Comment by HeavenVolkoff** [comment]
Forgot to add the CodecCommander to my answer...
I am also using the `ALCPlugFix` by  goodwin_c, but i don't think it would make any difference in this case. Even more, considering it didn't made much of a difference for me, because I need to replug the headphone jack and HDMI to get audio back after sleep.
Anyway, I hope you get audio working on your system.

**Comment by Piping** [comment]
Ok. And your headphone jack's sound works as well?

**Comment by HeavenVolkoff** [comment]
Except for the sleep bug, I don't have any other audio issue.

**Comment by illyriad** [comment]
Dear all, I'm running Ubuntu 19.10 (kernel: 5.3.0-23-generic) on my Macbook Pro 13,3, Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31), I have every solution around, still audio (built-in speakers) not working. Is there hope? Thanks for your response!

**Comment by ghost** [comment]
@illyriad you are running Ubuntu on a Mac pro? This thread is for DELL XPS 15 9550 running macOS >14
