### ISSUE TITLE
6% battery consumption in 9 hrs in STR mode

### ISSUE THREAD

**Issue by sven97** [wmchris/DellXPS15-9550-OSX#120]
Mojave 10.14.6 works pretty well on my machine. After the installation, I did run the script which disables the hibernation and changes it to normal STR (suspend to ram). I checked autopoweroff, standby, hibernatemode, diskleep and tcpkeepalive. They are all set to 0. The 0-byte sleepimage also created as wished.

According to wmchris, only 1% battery can last >12hrs. However, in my situation, the battery drops 6% in 9 hrs. 

So, I just want to ask is there anything I made a mistake during installation? Or is there anything I can do to improve the battery performance in STR?

My configuration is attached below:
Battery: 84Wh 4GVGH (replaced recently, new battery)
Processor: 2.3 GHz Intel Core i5
Memory: 16 GB 2133 MHz DDR4
Display: 15.6-inch (3840 x 2160)
Storage: 1TB Solid State PCI Express Driver

**Comment by krim404** [comment]
disable powernap.
