### ISSUE TITLE
Issue after upgrading to Catalina 10.15

### ISSUE THREAD

**Issue by achaheen** [wmchris/DellXPS15-9550-OSX#121]
Hi,
I have upgraded to Catalina and used the same Clover folder in 10.15 branch. The upgrade completed successfully but after I try to login to the new system it crash everytime and now I cannot use my hack!

Have anyone faced the same issue?

**Comment by golimpio** [comment]
I haven't this issue, but I've upgraded to Catalina a few betas ago. It's probably a good idea to ask this question on the [InsanelyMac forum](https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation/) as well, people over there might be able to help you.

**Comment by achaheen** [comment]
Thank you.

**Comment by achaheen** [comment]
I got it. 

You must create a new drive for installing Catalina then install the new version into it then after successfully install a fresh system the startup will ask you to migrate from older version or from backup then you can select your other drive with previous version and migrate your files from it. This requires your hack to have more space for creating extra drive. Hope this helps someone else.

**Comment by krim404** [comment]
most likely there are kexts residing from mojave in catalina. would be easier to fix than a reinstallation :-)
