### ISSUE TITLE
High battery usage after plugging in the AC adapter

### ISSUE THREAD

**Issue by fttx** [wmchris/DellXPS15-9550-OSX#122]
Hi,

i've an XPS 9550 FHD, everything works fine except this little issue with power management:
when I boot up the system, the PKG value immediately goes down to around 0,70W, but once i plug in the power cord it won't go lower than 6W. After unplugging the cable, it will go down for a second, and then back to 6-7W:

![image](https://user-images.githubusercontent.com/5663423/67162746-74e73000-f367-11e9-8968-3f3160f29c95.png)

I've also tried to:
- Disable SpeedStep from the BIOS
- Set config.plist/CPU/HWPEnable=false
- Put [SSDT-XCPM.aml](https://github.com/wmchris/DellXPS15-9550-OSX/blob/10.14/10.14/Post-Install/Additional%20Steps/Alternative%20Power%20Management/SSDT-XCPM.aml) in the `/EFI/CLOVER/ACPI/patched` folder

Am I missing something?

**Comment by solvar0719** [comment]
I've noticed the same problem. It seems to have been like this for quite a while.

**Comment by kiddj1** [comment]
Same prolem . Anyone have a solution to this? :(

**Comment by tiger511** [comment]
Does this happen with Windows too? I happens to me as well and i think its a bad motherboard.Please check with windows.Open task manager and plug in adapter and watch cpu usage.

**Comment by tiger511** [comment]
Try this solution: [https://github.com/xxxzc/xps15-9550-macos/issues/26](https://github.com/xxxzc/xps15-9550-macos/issues/26)
Worked for me.

**Comment by krim404** [comment]
As I don’t have this issue on my dev machine (now explained, because I don’t use the i2c personally) can another person confirm the fix using the disable-i2c0 ssdt? Then I push it in the repo.

**Comment by kiddj1** [comment]
> As I don’t have this issue on my dev machine (now explained, because I don’t use the i2c personally) can another person confirm the fix using the disable-i2c0 ssdt? Then I push it in the repo.

i dont know how to disable i2c0 ssdt but when i remove "8086,a160" from info.plist VoodooI2C. this issue is fixed. 

...sr for my bad english

**Comment by kiddj1** [comment]
> Try this solution: [xxxzc/xps15-9550-macos#26](https://github.com/xxxzc/xps15-9550-macos/issues/26)
> Worked for me.

tks for this solution

**Comment by golimpio** [comment]
> As I don’t have this issue on my dev machine (now explained, because I don’t use the i2c personally) can another person confirm the fix using the disable-i2c0 ssdt? Then I push it in the repo.

I've tried the disable-i2c0 ssdt and so far, it've worked for me:

```
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20190509 (64-bit version)
 * Copyright (c) 2000 - 2019 Intel Corporation
 * 
 * Disassembling to symbolic ASL+ operators
 *
 * Disassembly of iASLbAF1gc.aml, Thu Nov  7 16:41:33 2019
 *
 * Original Table Header:
 *     Signature        "SSDT"
 *     Length           0x00000052 (82)
 *     Revision         0x02
 *     Checksum         0x12
 *     OEM ID           "hack"
 *     OEM Table ID     "i2c0dsbl"
 *     OEM Revision     0x00000000 (0)
 *     Compiler ID      "INTL"
 *     Compiler Version 0x20180427 (538444839)
 */
DefinitionBlock ("", "SSDT", 2, "hack", "i2c0dsbl", 0x00000000)
{
    External (_SB_.PCI0.I2C0, DeviceObj)

    Scope (_SB.PCI0.I2C0)
    {
        Method (_STA, 0, NotSerialized)  // _STA: Status
        {
            Return (Zero)
        }
    }
}

```

CPU usage is a lot lower and frequency is also lower.
Thanks!

**Comment by krim404** [comment]
It’s impressive, that the reason for a higher power consumption after plugging in ac is a driver for the touchpad :) thank you guys for improving our setup

**Comment by krim404** [comment]
pushed to upstream. please close if this implementation fixed it.

**Comment by fttx** [comment]
I'm on 10.14, which file do I need to update?

**Comment by golimpio** [comment]
It worked for me (I'm on 10.15.1). Thanks for fixing it.

**Comment by krim404** [comment]
> I'm on 10.14, which file do I need to update?

See commit
