### ISSUE TITLE
My boot will panic the kernel, the system has been installed, just replaced the motherboard once

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#124]
![f56523b957209df5d1141ed18760028](https://user-images.githubusercontent.com/25170955/68440437-04189280-0206-11ea-9662-60ad14228881.jpg)
It seems that it's "EC", but I can't boot it and fix it. I don't have a second Mac OS device available. I hope you can help me

**Comment by ghsssss** [comment]
https://www.tonymacx86.com/threads/guide-usb-power-property-injection-for-sierra-and-later.222266/page-55#post-1728645

**Comment by krim404** [comment]
this is not a kernel panic. Also please write ONLY in english. 
The gui is not booting up. reinstall the system would be the easiest solution as i think this is an issue with old kexts.

If you dont want to reinstall: check all kexts, look for old ones in L/E and S/L/E. Also go thru the commit history of this repository and check for changes you could've missed.

i'll close this issue as it does not look like a problem with the repository.

**Comment by ghsssss** [comment]
Hello, I solve this problem because my win10 is a riod on installation. Choosing riod on to start Mac OS will cause many problems. It's OK to change back to achi.

**Comment by krim404** [comment]
ah this was a fresh installation? thought it was an update.

obviously raid is not supported.
I quote the tutorial:

> Don't forget to set mode to "AHCI" in the sub-menu "SATA Operation" of "System Configuration". It's mandatory.
