### ISSUE TITLE
Clover doesn't list the osx installer

### ISSUE THREAD

**Issue by sangra4l** [wmchris/DellXPS15-9550-OSX#128]
Hi,
I followed the guide before to install on my xps 15 osx 10.13.3.
Now i'm trying to do a fresh install of catalina but when i try to boot from usb my drive loads the new clover but it doesn't list the osx installer, only the boot from my ssd and the recovery.

Can anyone guide me to fix this issue?
Thanks

**Comment by golimpio** [comment]
For support and help, please try the forum, people might be able to help you over there: 

- https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation

Github issues are more for reporting bugs than for asking for support.

**Comment by krim404** [comment]
has nothing to do with this tutorial, as you dont have even started. you obviously need a working installation drive before you can start.

**Comment by fttx** [comment]
He is right, the Clover installer provided in the `Additional` folder won't list the macOS installer in the Clover menu.

**Comment by YanYangC** [comment]
Bump, having the same issue

**Comment by krim404** [comment]
no need to bump. use a newer clover version.

**Comment by wannadream** [comment]
@wmchris 
I tried with a newer Clove [v2.5k_r5101](https://github.com/Dids/clover-builder/releases/tag/v2.5k_r5101). After I removed and copied the whole directory, OSX installer was not listed.

**Comment by YanYangC** [comment]
Can confirm. I tried both installing clover r5101 from Dids GitHub release as well and not copying over the r5098 release from your GitHub repository, but copying over the rest of the files (kext, drivers, plist etc) as well as installing with the included clover then copying your repository, and copying the whole repository over a r5101 install, but all three yield the same no "install macOS from usb" option. I can, however, see that option if I boot using my existing clover install on my xps15  - which was created using the 10.14 guide and an older version of clover (think it was r4895?) - whilst having the 10.15 boot usb plugged in

**Comment by wannadream** [comment]
I installed r5101 and ONLY copied config.plist and kexts over. It did work but stuck on [this error](https://www.reddit.com/r/hackintosh/comments/6q9bwp/xps_9550_ftimerservicematching_timed_out/). If you need some further information, please let me know.

**Comment by krim404** [comment]
cannot replicate. please create a bootable stick with clover, where the usb device is visible, then copy only a part from the repository on the stick and tell me, which file makes the installer disappear.

**Comment by wannadream** [comment]
I will spend some time to do some detailed test and get the result back to you.

**Comment by wannadream** [comment]
I installed Clover v2.5_r5101, copied all kexts over and replaced config.plist. Installer showed up correctly but the process was stuck at some point. See screenshots.
![IMG_20191231_213742](https://user-images.githubusercontent.com/6989212/71638199-005a2880-2c17-11ea-9009-493cf67018d4.jpg)
![IMG_20191231_213759](https://user-images.githubusercontent.com/6989212/71638202-07813680-2c17-11ea-9945-5e0b69d28a04.jpg)
![IMG_20191231_213839](https://user-images.githubusercontent.com/6989212/71638204-0ea84480-2c17-11ea-8054-a67cbad74f45.jpg)

**Comment by JDevWebb** [comment]
I have managed to get it working, using the files from the 10.14 branch and copying those files onto the clover installation, and just replacing the entire kexts folder with the 10.15 one, you will be able to see the installer and boot into the installer. Not sure what files are causing the issue with the 10.15 branch.

**Comment by krim404** [comment]
can you please evaluate it further and identify which file does result in this behaviour?

**Comment by JDevWebb** [comment]
Will do, will get back to you.

**Comment by JDevWebb** [comment]
HFSPlus-64.efi appears to be missing from the 10.15 uefi drivers, adding this driver alongside the other 10.15 drivers allows the installation partition to be found by clover, however I personally am unable to boot the installer or my installation of Catalina, due to memory allocation issues, it must be one of the other drivers causing it but I am yet to determine which one is causing the memory issue. My hybrid of the 10.14 and 10.15 EFI files works fine booting Catalina, which the 10.15 drivers are not apart of.

**Comment by krim404** [comment]
strange, it was present in my master repository but not on github. I updated it. Should be fixed now.
