### ISSUE TITLE
No Sound Card installed on XPS 9560

### ISSUE THREAD

**Issue by valoricDe** [wmchris/DellXPS15-9550-OSX#130]
Hi there. I have the VerbStub.kext in my /L/Extensions and and hole lot of other kexts which i don't remember what they are for. Anyway - do I still need VerbStub for the Soundcard to work? Or do you have any other hints how to bring my sound back?
<img width="201" alt="Bildschirmfoto 2019-12-03 um 19 58 06" src="https://user-images.githubusercontent.com/22564188/70080725-5d0df780-1607-11ea-97fe-41e5512487a3.png">

**Comment by golimpio** [comment]
Have you followed the instructions?

- https://github.com/wmchris/DellXPS15-9550-OSX/blob/10.15/Tutorial_10.15_Step7.md#audio-fixes

VerbStub by itself won't help you, you need to follow the full instructions:

- https://github.com/wmchris/DellXPS15-9550-OSX/tree/10.15/10.15/Post-Install/Additional%20Steps/Audio/ComboJack

There is an install script in that folder.

**Comment by valoricDe** [comment]
I did now. I could not find it first because I was searching for VerbStub and not Combojack.
- I renamed my Volume from ESP to EFI.
- I mounted my read only partition `sudo mount -uw /`
- I ran `sudo ./install.sh` and got:
```
This installer requires admin rights. Also make sure you don’t have Time Machine running or any usb stick inserted!
Do you want to continue?
1) Yes
2) No
#? 1
Volume EFI on EFI mounted
Step 1: removing old content. 'Not found' errors are normal in this step
rm: /usr/bin/ALCPlugFix: No such file or directory
rm: /Library/LaunchAgents/good.win.ALCPlugFix.plist: No such file or directory
rm: /Library/Extensions/CodecCommander.kext: No such file or directory
Step 2: Adding files to your Library and EFI
Step 3: Updating Kext Caches
rm: /System/Library/PrelinkedKernels/prelinkedkernel: Read-only file system
touch: /System/Library/Extensions: Read-only file system
Step 4: Installing local configuration
cp: /usr/bin/ComboJack: Read-only file system
chown: /usr/bin/ComboJack: Read-only file system
cp: /usr/bin/hda-verb: Read-only file system
chown: /usr/bin/hda-verb: Read-only file system
/Library/LaunchAgents/com.XPS.ComboJack.plist: service already loaded

Please reboot! Also, it may be a good idea to turn off "Use
ambient noise reduction" when using an input method other than
the internal mic (meaning line-in, headset mic). As always: YMMV.

You can check to see if the watcher is working in the IORegistry:
there should be a device named "VerbStubUserClient" attached to
"com_XPS_SetVerb" somewhere within the "HDEF" entry's hierarchy.

Enjoy!
```
I checked IORegistry and can not find any VerbStubUserClient or com_XPS_SetVerb in HDEF
nor is any device listed in Sound Settings

**Comment by golimpio** [comment]
I believe you should have the sound working even without installing the ComboJack fix. Sorry, I forgot to mention it, the combojack will fix the issue with plugging a headphone (usually it doesn't recognise the headphone without this fix).

The  AppleALC.kext (included in this repo) should be enough to have the audio working if you're using the config.plist and drivers from the repository (everything is already configured).

Unfortunately I can't help you more, since I never had an issue with the audio, other than the headphone.

**Comment by ghost** [comment]
The script is telling your system is read only. I don't think is writing the kext to its location. You have / as a read only ?

**Comment by valoricDe** [comment]
@hackedWifi Yes it was telling me that it is read only but I did `csrutil disable` and `mount -uw /` and the install.sh replaced my old VerbStub.kext with the new one. I checked.
The funny thing is that it was working with AppleALC.kext and the configuration below with OSX 10.13.3. So I'm really uncertain what it is. @golimpio do you have a layout28 or layout72 file in your /System/Library/Extensions/AppleHDA.kext/Contents/Resources?
```
<devices....
		<key>Audio</key>
		<dict>
			<key>Inject</key>
			<string>28</string>
		</dict>
```

**Comment by golimpio** [comment]
I'm using *layout-id* **30** (base64: **HgAAAA==**, hex: **0x1e**).

The original from this repository was working fine in *10.15*, I've changed it to test if it would change the combo jack behaviour (some people have reported that it worked better with *layout-id* **30**, but it wasn't my case, it didn't help).

That's from my `clover/config.plist`:

```
  <key>Devices</key>
  <dict>
    <key>Properties</key>
    <dict>
      <key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
      <dict>
        <key>layout-id</key>
        <data>HgAAAA==</data>
      </dict>
```

I'm not sure why you're changing your `S/L/E/AppleHDA`, there is no need to change system kexts directly.

My full `clover/config.plist` in case you'd like to compare it:

- https://gist.github.com/golimpio/afd1bde9df343b075ba4ca51bb69897c

**Comment by krim404** [comment]
WAIT! He has a 9560. This tutorial is for the 9550.
Please use the correct tutorial for your machine in the first place - and dont mix files between them. Most 9560 builds are using different layout-ids and so the scripts in this repository will not fit.
