### ISSUE TITLE
Update VoodooI2C

### ISSUE THREAD

**Issue by fttx** [wmchris/DellXPS15-9550-OSX#131]
A new version has been released: https://github.com/alexandred/VoodooI2C/releases

Do you plan to update it?

**Comment by krim404** [comment]
just change the files and take a look if everything works. :-)

**Comment by fttx** [comment]
Nope, it breaks the sleep wake up

**Comment by krim404** [comment]
well, then i close it for now. please also report this in the bugtracker from voodooI2C, maybe they can fix it

**Comment by fttx** [comment]
https://github.com/alexandred/VoodooI2C/issues/231
