### ISSUE TITLE
voodoops2controller.kext causes panics

### ISSUE THREAD

**Issue by agrafuese** [wmchris/DellXPS15-9550-OSX#132]
`*** Panic Report ***
panic(cpu 0 caller 0xffffff800aedc9bd): Kernel trap at 0xffffff7f8e73aca8, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x0000000023ba1000, CR4: 0x00000000003626e0
RAX: 0xfa424d5d87c8003d, RBX: 0xffffff8040e84000, RCX: 0x0000000000000008, RDX: 0xffffff7f8e742470
RSP: 0xffffff81ff7b3d60, RBP: 0xffffff81ff7b3d70, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0xffffff81be441200, R9:  0xffffff81be4411fc, R10: 0xffffff81be441000, R11: 0x0000000000000000
R12: 0xffffff8042292d50, R13: 0xffffff8042292d58, R14: 0xffffff80420db800, R15: 0xffffff8042292d00
RFL: 0x0000000000010286, RIP: 0xffffff7f8e73aca8, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffff81ff7b3830 : 0xffffff800adaf57d 
0xffffff81ff7b3880 : 0xffffff800aeeb065 
0xffffff81ff7b38c0 : 0xffffff800aedc79a 
0xffffff81ff7b3930 : 0xffffff800ad5c9d0 
0xffffff81ff7b3950 : 0xffffff800adaef97 
0xffffff81ff7b3a70 : 0xffffff800adaede3 
0xffffff81ff7b3ae0 : 0xffffff800aedc9bd 
0xffffff81ff7b3c50 : 0xffffff800ad5c9d0 
0xffffff81ff7b3c70 : 0xffffff7f8e73aca8 
0xffffff81ff7b3d70 : 0xffffff800b42baaa 
0xffffff81ff7b3dc0 : 0xffffff800b4374bb 
0xffffff81ff7b3df0 : 0xffffff7f8e73a531 
0xffffff81ff7b3e20 : 0xffffff7f8e741d5d 
0xffffff81ff7b3e40 : 0xffffff800b42f6cb 
0xffffff81ff7b3e80 : 0xffffff800b42f385 
0xffffff81ff7b3f00 : 0xffffff800b42e947 
0xffffff81ff7b3f50 : 0xffffff800b430436 
0xffffff81ff7b3fa0 : 0xffffff800ad5c0ce 
      Kernel Extensions in backtrace:
         as.acidanthera.voodoo.driver.PS2Trackpad(2.0.4)[CFDA888E-E3F7-3220-BE69-F6C46E719297]@0xffffff7f8e739000->0xffffff7f8e748fff
            dependency: as.acidanthera.voodoo.driver.PS2Controller(2.0.4)[E2927F57-AEFE-372E-ACAD-19C77D1D69E9]@0xffffff7f8e6d0000
            dependency: com.apple.iokit.IOHIDFamily(2.0.0)[CCEA17E9-B816-3148-AFF1-E43E46E1C37B]@0xffffff7f8bc0e000

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 nv_disable=1 agdpmod=vit9696 -v brcmfx-country=#a darkwake=no -lilubetaall kext-dev-mode=1 

Mac OS version:
18G1012

Kernel version:
Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64
Kernel UUID: DFB5D0E2-3B41-3647-A48B-D704AFCC06B4
Kernel slide:     0x000000000aa00000
Kernel text base: 0xffffff800ac00000
__HIB  text base: 0xffffff800ab00000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

System uptime in nanoseconds: 6834762454
last loaded kext at 3353261784: com.apple.driver.AppleActuatorDriver	2450.1 (addr 0xffffff7f8df64000, size 61440)
loaded kexts:
com.alexandred.VoodooI2CHID	1
com.no-one.BrcmPatchRAM2	2.2.10
com.no-one.BrcmFirmwareStore	2.2.10
com.metakine.handsoff.driver	4.2.1
as.acidanthera.voodoo.driver.PS2Mouse	2.0.4
as.acidanthera.voodoo.driver.PS2Trackpad	2.0.4
as.acidanthera.voodoo.driver.PS2Keyboard	2.0.4
org.rehabman.driver.FakePCIID	1.3.15
ru.joedm.SMCSuperIO	1.0.2
com.alexandred.VoodooI2C	2.2
org.coolstar.VoodooGPIO	1.1
as.acidanthera.voodoo.driver.PS2Controller	2.0.4
as.vit9696.SMCProcessor	1.0.2
xyz.racermaster.NoTouchID	1.0.1
as.lvs1974.AirportBrcmFixup	1.1.9
as.vit9696.AppleALC	1.3.6
org.tw.CodecCommander	2.7.1
as.vit9696.WhateverGreen	1.2.7
ru.usrsse2.SMCBatteryManager	1
org.vanilla.driver.CPUFriend	1.1.6
ru.usrsse2.SMCLightSensor	1
as.vit9696.VirtualSMC	1.0.2
as.vit9696.Lilu	1.3.5
com.alexandred.VoodooI2CServices	1
com.apple.driver.AppleTopCaseHIDEventDriver	138.4
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.driver.AppleVirtIO	2.1.3
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.filesystems.apfs	945.275.8
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.driver.AppleAHCIPort	329.260.5
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleBacklight	170.12.12
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	202
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleActuatorDriver	2450.1
com.apple.driver.AppleHSBluetoothDriver	138.4
com.apple.driver.IOBluetoothHIDDriver	6.0.14d3
com.apple.iokit.IOBluetoothFamily	6.0.14d3
com.apple.driver.AppleMultitouchDriver	2450.1
com.apple.driver.AppleInputDeviceSupport	2440.2
com.apple.driver.AppleUSBAudio	315.6
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.iokit.IOSerialFamily	11
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleUSBMergeNub	900.4.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOAHCIBlockStorage	301.270.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEFIRuntime	2.1
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530.51
com.apple.iokit.IOGraphicsFamily	530.67
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.260.3
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.250.3
com.apple.iokit.IOSCSIArchitectureModelFamily	408.250.3
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.CoreTrust	1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	740.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF`

**Comment by krim404** [comment]
did you disable the SD-Card reader in bios?

**Comment by agrafuese** [comment]
Hi wmchris, 

Yes - this is agrafuese from insanelymac. I updated my posted over there to confirm that this version still gives me KPs after the SD card is disabled. But keep in mind, the older version still works great and loads my keyboard 100% of the time. I wanted to write the KP issue here so that others can see it as well. I really wish the newer version worked for me, because I like that I can use ANSI as my keyboard setting (I have to use ISO to get the ` key to work). Thank you for responding.

**Comment by krim404** [comment]
sorry i cant keep track with every issue right now. you get this KP with a new version of voodoops2? or with the old one? 
old+sd? new+sd? both?

**Comment by golimpio** [comment]
Have you tried the new `VoodooPS2Controller.kext` without `VoodooI2C.kext`? I think you'd have to add the new `VoodooInput.kext` in order to test it.

**Comment by agrafuese** [comment]
> sorry i cant keep track with every issue right now. you get this KP with a new version of voodoops2? or with the old one?
> old+sd? new+sd? both?

SD card disabled with both versions.
KP happens with newest (Nov 8) version (in the 10.14 branch).
No KPs with version from Feb 9.
Thank you.

> Have you tried the new `VoodooPS2Controller.kext` without `VoodooI2C.kext`? I think you'd have to add the new `VoodooInput.kext` in order to test it.

I have not tried this. Do you have a link to the VoodooInput.kext you're referring to? And is this also for 10.14? Thank you.

**Comment by golimpio** [comment]
Link:

- https://github.com/acidanthera/VoodooInput

As per release note, in 1.0.1 they've added support for versions prior to 10.15.
A can confirm it works well on 10.15.2, but I have no idea if it works on 10.14.

**Comment by agrafuese** [comment]
I would really like to test that and report back with my findings, but it appears those files are all in an uncompiled c++ format (?), which is well beyond my area of expertise :) Sorry.

**Comment by golimpio** [comment]
They should have the compiled kexts in the release:

https://github.com/acidanthera/VoodooInput/releases

**Comment by agrafuese** [comment]
Thanks for showing me the way. I barely understand how certain parts of this site work sometimes. Anyway, I have the kext loaded up now, took out VoodooI2C as you suggested. So far, I have been able to boot up twice with keyboard working and no KPs, but now the trackpad isn't working. Oddly enough, the touchscreen DOES still work - I thought I saw wmchris tell you (on insanelymac) that VoodooI2C is for touchscreen, so I'm confused as to why it works after I removed it. Is that strange?

**Comment by golimpio** [comment]
Usually the trackpad works after a reboot, which is normal. The last time I've upgrade my MacOS, it took me more than 5 reboots for it to work, and I can't really explain why this happened.

As for the touchscreen, one possible explanation is that this kext (VoodooInput) probably uses some code from VoodooI2C, and the touchscreen part of it is implemented. Or, maybe the touchscreen just works as a trackpad for the kext, but I'm just guessing.

**Comment by agrafuese** [comment]
Wow, you're absolutely right. It took many reboots before the trackpad came to life. I've been a hackintosh user on and off over the last 12 years, and this is definitely one of the more bizarre things I've experienced. Anyway, so far no KPs with newest voodoops2 + voodooinput, but I'm not making any definitive statements until I have a consistent streak of successful reboots for the next week. Thanks for all the help up to this point. I will report back.

**Comment by agrafuese** [comment]
Just wanted to update: 10 days into using VoodooInput instead of VoodooI2C, system is still running very well, no KPs have occurred, and keyboard has worked upon reboot every time. I approximate that I have rebooted my system roughly 20-40 times over this period so far. Essentially, it appears that VoodooInput (versus VoodooI2C) is the proper pairing with VoodooPS2controller. 

I do not have any information as to whether or not other less noticeable issues exist after swapping the two kexts. For example, if there are now power consumption issues, I have not experienced them in any obvious way. 

At this time, I do believe this issue can be marked as solved unless you'd like me to investigate further. Thanks, especially to golimpio, for helping me figure this out.
