### ISSUE TITLE
Upgrade to 10.15.4

### ISSUE THREAD

**Issue by achaheen** [wmchris/DellXPS15-9550-OSX#134]
Hi,
I upgraded to 10.15.4 after deleting kexts in /Library/Extensions and after upgraded Lilu and Whatevergreen kexts but the wifi and bluetooth drivers failed. I feel it's USB mapping issue so I advice everyone to wait before upgrading until we found a solution for this issue. If anyone has updated without issue please let we know where is the issue exactly to resolve it. 

Thanks.

**Comment by krim404** [comment]
well there are multiple reports of working 10.15.4 on the system...
more info in the forumthread.
