### ISSUE TITLE
when I update  to 10.15.4 (19E287) 

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#135]
when I update  to 10.15.4 (19E287) 。the clover vesion is 51xx，entering the system will get stuck, but you can enter it after more than 10 seconds. At this time, the system loading interface has passed.

**Comment by krim404** [comment]
?? Please explain better where when what gets stuck?
Which interface?

**Comment by ghsssss** [comment]
sry,no problem,thanks
