### ISSUE TITLE
Problem with newest clover version - kernel panic

### ISSUE THREAD

**Issue by koenheemskerk** [wmchris/DellXPS15-9550-OSX#136]
Hi all. 
I get the error "An error occurred while preparing the installation. Try running this application again." 5 minutes after starting the install of Catalina 10.15.6. Followed the guide closely and I have done everything correctly as far as I know. 
The installer log shows: "unable to get fs for /macos install data" and later "disk1s1 is not convertible to APFS: You may not install on this volume..."

I'm using a freshly installed Crucial P1 500GB NVMe SSD.

**Comment by krim404** [comment]
i updated the files for 10.15.6. Can you try again?

**Comment by koenheemskerk** [comment]
Sorry I'm trying to install 10.15.7 actually. Latest OS from Apple.

Will try again!

**Comment by krim404** [comment]
should be compatible with 10.15.7 as well. i checked it on my local testmachine (pulled from working condition). You can also try to use OC, which is more cryptic when you have problems, but is working as well.

**Comment by koenheemskerk** [comment]
I made a new EFI partition on the USB but now, when I boot into clover I get the error message:
"Cannot find config.plist/Quirks
A Fatal error happened. System halted."

**Comment by krim404** [comment]
ah sorry i forgot the new quirks entry in the demo configuration. I'll add that afap
Can you try using OC?

EDIT: added.

**Comment by koenheemskerk** [comment]
I will. Have to look for a tutorial as I'm not experienced with Hackintosh.

Thanks for adding.

**Comment by krim404** [comment]
The OC version should work the same way as the Clover version, you just need to refer to the folder OC instead of CLOVER.

BTW:
https://github.com/CloverHackyColor/CloverBootloader/issues/247

**Comment by koenheemskerk** [comment]
OC gives me Err (0xE) @ GV wake-failure.

Clover now gives [red letter] "Error: Not Found returned from DataHubDxe.efi". Then shows up as normal clover bootloader but ends with a kernel panic.  [cpu 0 caller], after I boot MacOS install.

**Comment by krim404** [comment]
meh. Clover updated to a new version with quirks, which breaks a lot of stuff.

Try:
```
add
<key>DisableIoMapper</key>
<true/>
in the  Quirks section, then remove DataHubDxe.efi from
"CLOVER/drivers/UEFI"
```

**Comment by koenheemskerk** [comment]
Red error text is gone, but the kernel panic persists. Is there a way of using an older version of Clover perhaps?

**Comment by krim404** [comment]
obviously, just download the version from two weeks ago

**Comment by koenheemskerk** [comment]
Okay. Thanks. After reading a lot, I'm also wondering; I'm using a USB-C PD charger to charge the device. Might that be interfering with something IO related?

**Comment by krim404** [comment]
i do this as well, without any problem so far.

**Comment by krim404** [comment]
I changed the title, as i keep it open till the clover problem has been fixed. until then i would suggest using opencore - but this is a lil bit more complicated to set up.

**Comment by koenheemskerk** [comment]
Thanks for all the help.

**Comment by lamhoangtung** [comment]
@wmchris Are there any benefit of using OpenCore ? BTW, how's the installation process will need to be change compare to Clover ? Thanks

**Comment by krim404** [comment]
i updated the tutorial for opencore. Its just a cleaner setup and with the last problems with Clover, i dont see any reason to continue supporting clover.
