### ISSUE TITLE
Have you updated the latest system

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#137]
The new version of clover seems difficult to configure, and the new version of MacOS does not support 60Hz 4K

**Comment by duc-td** [comment]
I am waiting for EFI for Big Sur

**Comment by zycer** [comment]
> I am waiting for EFI for Big Sur

Me too.

**Comment by krim404** [comment]
It will take a few days, as i dont have time to immediately update it. 
It should be compatible when using OpenCore without much effort.
TBH i think i will switch this repository very soon to OpenCore only, as Clover had some very nasty bugs in the past months.

**Comment by zycer** [comment]
> It will take a few days, as i dont have time to immediately update it.
> It should be compatible when using OpenCore without much effort.
> TBH i think i will switch this repository very soon to OpenCore only, as Clover had some very nasty bugs in the past months.

Okay, waiting for your good news!

**Comment by nmhendriks75** [comment]
Great :) Also awaiting good news

**Comment by azeezsker** [comment]
Thanks wmchris for your hardwork, waiting to update to Big Sur with your updated OC Repo.

**Comment by golimpio** [comment]
If anyone is interested in testing Big Sur 11.0.1 with OpenCore, be aware that quite a few people with this laptop, including myself, are experiencing the same error: _"OCB: StartImage failed-Aborted"_

I'm making some progress, but for now it's just a workaround and I couldn't find anyone that have fixed it yet, see my post here:
https://github.com/xxxzc/xps15-9550-macos/issues/74#issuecomment-732144560

**Comment by krim404** [comment]
can confirm - i have issues which were not there with the Big Sur Beta. I do not recommend updating yet. Too high chance for a broken system.

**Comment by golimpio** [comment]
@wmchris 

I'm attaching the EFI I'm using for testing Big Sur, it works for the stable version and also for the new Beta (11.1). A few people already tested it, so I think it's good for who are interested in getting started with Big Sur.

I haven't found any issue yet, but graphics performance seems to have decreased, but I also noticed it when I first updated to Catalina, and since I do a lot of photo editing, this is bad news to me, but at least, overall, Big Sur feels very responsive for this laptop.

The `config.plist` is a bit big, since I've tried to include all the entries, including the default values. I think this is recommended, because there is no guarantee that the default values won't change in the future.

I'm using OpenCore 0.6.3, and I've updated the kexts to the latest releases.

**NOTE:** My config.plist is optimised for the 4K version, which means that I have an extra setting (EDID) to change the display to 48Hz.

[EFI.zip](https://github.com/wmchris/DellXPS15-9550-OSX/files/5593573/EFI.zip)

**Comment by duc-td** [comment]
> @wmchris
> 
> I'm attaching the EFI I'm using for testing Big Sur, it works for the stable version and also for the new Beta (11.1). A few people already tested it, so I think it's good for who are interested in getting started with Big Sur.
> 
> I haven't found any issue yet, but graphics performance seems to have decreased, but I also noticed it when I first updated to Catalina, and since I do a lot of photo editing, this is bad news to me, but at least, overall, Big Sur feels very responsive for this laptop.
> 
> The `config.plist` is a bit big, since I've tried to include all the entries, including the default values. I think this is recommended, because there is no guarantee that the default values won't change in the future.
> 
> I'm using OpenCore 0.6.3, and I've updated the kexts to the latest releases.
> 
> **NOTE:** My config.plist is optimised for the 4K version, which means that I have an extra change (EDID) to change the display to 48Hz.
> 
> [EFI.zip](https://github.com/wmchris/DellXPS15-9550-OSX/files/5593573/EFI.zip)

Is your Bluetooth working?

**Comment by golimpio** [comment]
> Is your Bluetooth working?

Yes, Bluetooth is working.

**Note:** I haven't tried to connect it to an external monitor yet, I think this is the only thing that I haven't tested compared to the Catalina version. I also don't have any thunderbolt device, so I can't give feedback on it.

**Comment by duc-td** [comment]
> > Is your Bluetooth working?
> 
> Yes, Bluetooth is working.
> 
> **Note:** I haven't tried to connect it to an external monitor yet, I think this is the only thing that I haven't tested compared to the Catalina version. I also don't have any thunderbolt device, so I can't give feedback on it.

![20201125_130047](https://user-images.githubusercontent.com/54102426/100189280-90374e00-2f1e-11eb-8101-2bc765e090c7.jpg)
I cannot boot with your EFI

**Comment by golimpio** [comment]
> I cannot boot with your EFI

I don't expect that my EFI will work for everybody, although it's complete, it's more like an example and it's missing the serial/model numbers. So I'm assuming that you've fix this and cleaned the NVRAM before trying to run the Install.

I'm not familiar with the error, maybe if you attach the log file from OpenCore, it would give us some more details about the issue (https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html).

**Comment by krim404** [comment]
this will be displayed before the kernel is loaded.
i'll check your EFI this weekend on my machine and do the usual QA (aka plugging in everything i can find).

**Comment by duc-td** [comment]
> > I cannot boot with your EFI
> 
> I don't expect that my EFI will work for everybody, although it's complete, it's more like an example and it's missing the serial/model numbers. So I'm assuming that you've fix this and cleaned the NVRAM before trying to run the Install.
> 
> I'm not familiar with the error, maybe if you attach the log file from OpenCore, it would give us some more details about the issue (https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html).

Thanks <3

**Comment by krim404** [comment]
i'm still having problems with big sur. it works, but only a part of it. i cant get the external adapters to work with it.

**Comment by golimpio** [comment]
Unfortunately I don't have many external adapters to help testing it. I have tested the connection to an external 4k monitor, connected to the thunderbolt through a display port adapter and it worked fine. The others peripherals I own are just simple USB devices: external Seagate drive for backup, Sony camera (usb-c) and iPhone, and I guess these types of peripherals shouldn't be an issue to anyone. Bluetooth devices like external speakers and mouse are working fine. Handoff with iPhone is working fine.

**Comment by krim404** [comment]
i have issues with the usb-c docks. neither the small nor the big are working. this includes the VGA adapter and ethernet. but i think i have a clue how to fix it.

**Comment by duc-td** [comment]
Do you get an error when the screen will flicker from sleep mode, the only way is to reboot?

**Comment by azeezsker** [comment]
I was able to considerably reduce screen flickering on Big Sur by boot arguments -cdfon and -disablegfxfirmware, dont know how it works though.

**Comment by duc-td** [comment]
> I was able to considerably reduce screen flickering on Big Sur by boot arguments -cdfon and -disablegfxfirmware, dont know how it works though.

Thank you, I am testing

**Comment by golimpio** [comment]
> Do you get an error when the screen will flicker from sleep mode, the only way is to reboot?

Someone in the forum has reported a way to fix this, not sure if it works for everyone, but it worked for me:

- https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation/?do=findComment&comment=2742601

**Comment by duc-td** [comment]
> > Do you get an error when the screen will flicker from sleep mode, the only way is to reboot?
> 
> Someone in the forum has reported a way to fix this, not sure if it works for everyone, but it worked for me:
> 
> * https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation/?do=findComment&comment=2742601

Thank you, this phenomenon has decreased a lot when I tried this. But it is still there

**Comment by azeezsker** [comment]
Is someone able to run clover with Big Sur? How is it doing?

**Comment by ghsssss** [comment]
我成功了，Intel Wi-Fi～

**Comment by ghsssss** [comment]
When you use it, does it get too heavy? When I was testing with UFOS, the frames often dropped by 30

**Comment by krim404** [comment]
i updated the tutorial for bigsur. The config is a streamlined and slightly performance optimized version of XXXCZs installation. His repository included most of the configuration i used in my own individual setup before - not much i can improve. Great work!
