### ISSUE TITLE
Clarification in the tutorial for OpenCore Big Sur?

### ISSUE THREAD

**Issue by lamhoangtung** [wmchris/DellXPS15-9550-OSX#138]
Hi. I'm interested in upgrading to BigSur. I heard that you switched to OpenCore for the Big Sur version. But in the tutorial it still said CLOVER ? I haven't use OpenCore before so I'm not sure this is correct or this is a typo ? Can you confirm this @wmchris 

![image](https://user-images.githubusercontent.com/26834698/102763549-6bfb4f80-43ac-11eb-9b81-9ead00e368ef.png)

**Comment by ghost** [comment]
@lamhoangtung The folder OC means Open Core my man. No clover anymore because it sucks. Open Core it is way better. I read this and it was difficult but I did it on my own.
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html#downloading-macos

**Comment by lamhoangtung** [comment]
Thanks @wmchris and @hackedWifi

**Comment by lamhoangtung** [comment]
Also, can you clarify this sentences in the tutorial a bit more @wmchris 

```
You have to enter a valid serial number, MLB and other variables (so called SMBIOS) to the config.plist in EFI/OC/.
```

The previous version using Clover doesn't had this step. I also had a few question related to this sentences:
1. I thought SMBIOS was pre-selected by your OC config ?
2. How to generate a valid serial number, before when using Clover I used Clover Configurator ? How about OpenCore ?
3. Can I change the serial number afterward like Clover or I must preconfig it before install ?
4. What is MLB ? I can't seem to figure it out ;(
5. What is "other variables" ? Can you help us highlight it and when to change any of it ?

Again, thanks for the amazing work chris <3

**Comment by ghost** [comment]
@lamhoangtung You are obviously not reading the link I gave you. You must read. All the information is there. This repo is for Open Core not Clover anymore. Do your homework then feel free to ask questions.

**Comment by lamhoangtung** [comment]
@hackedWifi I'm still reading it but I only seems to find out the answer for the serial number and MLB. But I haven't found out the answer for the question 1, 3 and 5. Any hint would be very helpful

Anyway, I apologize if I'm upset you or bother you too much ;(

**Comment by lamhoangtung** [comment]
Some clarification for my own question for anyone needed this in the future:
1. SMBIOS was preselected, it is `MacBookPro13,3` for the XPS 15 9550
2. You can refer this part to generate a valid serial number (an related number too): https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial
3. I guess not, I did this before the installation process
4. MLB = Board Serial
5. Other variables in this case is SMBIOS related number, which is:
```
  Type = SystemProductName
  Serial = SystemSerialNumber
  Board Serial = MLB
  SmUUID = SystemUUID
```
