### ISSUE TITLE
Wrong boot resolution on OpenCore

### ISSUE THREAD

**Issue by lamhoangtung** [wmchris/DellXPS15-9550-OSX#139]
Hi. Thank for the amazing work @wmchris. I've been following this tutorial and install the latest version of BigSur working flawlessly. But there are only one problem left:

After finish install, I follow this to clean up the boot process: https://dortania.github.io/OpenCore-Post-Install/cosmetic/verbose.html#macos-decluttering

Then I notice the boot logo (Apple logo) was render in the wrong resolution, probably 800x600 before switching to the proper 1920x1080 (my XPS 15 is 1080p) when the progress bar loaded halfway through.

But after trying to set `Resolution` to `Max` or `1920x1080` or `1920x1080@32`, messing with `ProvideConsoleGop` and `ForceResolution` after reading the `Configuration.pdf` of OpenCore. The boot logo still being render with the same 800x600 resolution.

Are you having this issue ? If no, are there anything that I'm doing wrong here. It would be great if you can help me point it out. Thanks

**Comment by golimpio** [comment]
I don't have this issue with the 4k version of the laptop. Sorry for the basic question, but when you changed the UIScale to **01**, did it affect the boot logo?

I'm assuming that you have the following settings on _NVRAM_: 
```
<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
<dict>
	<key>UIScale</key>
	<data>AQ==</data>
</dict>
```

**Comment by lamhoangtung** [comment]
Actually I'm having this:
```
	<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
	<dict>
		<key>UIScale</key>
		<data>
		Ag==
		</data>
	</dict>
```

But changing the UIScale to 01 make the logo display properly. Thanks a lot for the help @golimpio
