### ISSUE TITLE
Retaining brightness after reboot?

### ISSUE THREAD

**Issue by scottsanett** [wmchris/DellXPS15-9550-OSX#14]
I just read somewhere else that it's now possible to retain brightness after reboot but I don't see any mention of this in your guide. I wonder if there's any recent change in your clover configuration. Would you mind elaborating on this topic?

**Comment by wmchris** [comment]
no need for change in the configuration. just install clover and also select the rc scripts. i'll write it in step 7.

**Comment by wmchris** [comment]
(btw it was mentioned before, but most people forgot to do the step and it was not explained what this step will do)

**Comment by scottsanett** [comment]
@wmchris Strange, I installed Clover with `install rc scripts to target location` and still the laptop reboots with maximum brightness. There is a nvram.plist in my EFI that changes as I tune brightness up and down and I don't see any errors in Boot.log. I wonder if something else is wrong.

**Comment by scottsanett** [comment]
Yep, just followed this guide [[solved] Backlight turns to full brightness after sleep or restart!](https://www.tonymacx86.com/threads/solved-backlight-turns-to-full-brightness-after-sleep-or-restart.192065/page-4) and solved the problem.
