### ISSUE TITLE
Reminder for when updating BrcmBluetoothInjector.kext

### ISSUE THREAD

**Issue by golimpio** [wmchris/DellXPS15-9550-OSX#142]
​This is not an issue, just a reminder for changing the `config.plist` before updating `BrcmBluetoothInjector.kext`.

For more background information, look for the notes at the official repository:
- https://github.com/acidanthera/BrcmPatchRAM#brcmbluetoothinjectorkext

**TLDR:** _"The BrcmBluetoothInjector.kext is a codeless kernel extension which injects the BT hardware data using a plist"_, this means that we have to remove the path to the `BrcmBluetoothInjector` executable in the `config.plist` file, otherwise it will fail to boot.

This is the code to be removed:
```
<key>ExecutablePath</key>
<string>Contents/MacOS/BrcmBluetoothInjector</string> 
```

**Comment by golimpio** [comment]
I won't change this now because we still have the old `BrcmBluetoothInjector.kext` in this repository, and it seems to be working fine. Updating the `BrcmBluetoothInjector.kext` probably would require more tests in order to make sure it's working for everyone else (or must of us).

**Comment by krim404** [comment]
seems to work
