### ISSUE TITLE
Updating OpenCore to 0.6.6

### ISSUE THREAD

**Issue by golimpio** [wmchris/DellXPS15-9550-OSX#143]
Note that it's not necessary to update _OpenCore_ in order to update _Big Sur_ to `11.2`.

So this is just a reminder that there are some minor changes that require a small modification in the `config.plist` file.

As far as I noticed, if we just remove `BootProtect` it should work fine:

```
<key>BootProtect</key>
<string>None</string>
```

Even if we don't remove it, it should still work with a warning message before the boot menu, but it's easy enough to remove it when updating _OpenCore_, so we avoid deprecated code that can cause boot failure in future _OC_ versions.

Release notes:
- https://github.com/acidanthera/OpenCorePkg/releases/tag/0.6.6

Also:
- https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html#updating-bootstrap-in-0-6-6

**Comment by krim404** [comment]
thanks :-)
