### ISSUE TITLE
Kernel Panic- Can't perform Kext scan : no kext summary

### ISSUE THREAD

**Issue by azeezsker** [wmchris/DellXPS15-9550-OSX#148]
Repo dated 08 Apr 2021 causing KP with above message, appreciate any help to resolve, thanks.

**Comment by golimpio** [comment]
I couldn't replicate your issue, I'll wait for @wmchris and see if this version is causing issues for him as well. In the meantime, if you have any fix for this, please share.

I've tested with the exactly same files in the repository, I've just changed the values for the serial numbers:

- ```<key>MLB</key>```
- ```<key>SystemSerialNumber</key>```
- ```<key>SystemUUID</key>```

I have the 4k version of the XPS 9550 16GB, with a replaced SSD: WDC WDS100T2B0C-00PXH0. I don't think this should make any difference though.

Software:

- macOS 11.2.3 (20D91)
- OpenCore 0.6.8

The steps I've done while testing this:

1. Replaced the content of my OC EFI volume (```/Volumes/EFI/EFI/OC```) with the repo content (```.../DellXPS15-9550-OSX/11.0/OC```)
2. Replaced the boot EFI file (```/Volumes/EFI/EFI/BOOT/BOOTx64.efi```) with the one from the repo (```.../DellXPS15-9550-OSX/11.0/BOOT/BOOTx64.efi```)
3. Changed the serial numbers as mentioned above.
4. Rebooted it

**Comment by golimpio** [comment]
If anyone wants to go back to the version before ```08 Apr 2021```, run the following from the command line:

```
git checkout 5cea1e2d36d3478abc0d72c004ee81efcc8af7a0
```

It will reverse to the latest commit before my changes. See:

- [https://github.com/wmchris/DellXPS15-9550-OSX/commit/5cea1e2d36d3478abc0d72c004ee81efcc8af7a0](https://github.com/wmchris/DellXPS15-9550-OSX/commit/5cea1e2d36d3478abc0d72c004ee81efcc8af7a0)

**Comment by golimpio** [comment]
Additional information:

- [https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#kernel-panic-cannot-perform-kext-summary](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#kernel-panic-cannot-perform-kext-summary)

**Comment by azeezsker** [comment]
Thank you and WMChris for your hard work and support.

Found out that opencanopy in combination with ProperTree OCsnapshot was the cause of problem (may be messing up the kext order). Removed opencanopy and booted successfully, will report any problem if found.

Best Regards

**Comment by golimpio** [comment]
It's good to know, thanks for your feedback. Please note that the _OpenCanopy_ has to be the same version as the  ```OpenRuntime.efi``` according to them. 

I have ```OpenCanopy.efi``` working in my setup for the OC GUI, but I didn't push it to the repository as it's not necessary if you aren't using OC GUI.

Anyway, like you said, it might be the ProperTree editor, but also make sure you have the ```OpenCanopy.efi``` from the OC 0.6.8 release. 

I usually do all my edits in [TextMate 2](https://github.com/textmate/textmate).

That's my settings for the drivers in the ```config.plist```:

```
	<key>Drivers</key>
	<array>
		<string>AudioDxe.efi</string>
		<string>HfsPlus.efi</string>
		<string>OpenCanopy.efi</string>
		<string>OpenRuntime.efi</string>
	</array>
```

```AudioDxe.efi``` is not mandatory, it was my attempt to turn on the "Chime" boot sound, but it's not working at the moment.
