### ISSUE TITLE
Could you please give me a set of Intel WiFi configuration EFI

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#149]
Could you please give me a set of Intel WiFi configuration EFI

**Comment by golimpio** [comment]
Have you checked out this project?
- https://github.com/xxxzc/xps15-9550-macos#intel-wireless-card

**Comment by ogaponcic** [comment]
> Could you please give me a set of Intel WiFi configuration EFI

Hi, if it is still actual, you can try my fork:
https://github.com/ogaponcic/DellXPS15-9550-OSX/tree/11.0-INTEL8260

**Comment by ghsssss** [comment]
> > Could you please give me a set of Intel WiFi configuration EFI
> 
> Hi, if it is still actual, you can try my fork:
> https://github.com/ogaponcic/DellXPS15-9550-OSX/tree/11.0-INTEL8260

could you update It？

**Comment by ogaponcic** [comment]
Yeap. I will update it today. I was waiting for new versions of intel wifi && bt kexts.
