### ISSUE TITLE
How about the DisplayPort?Work?

### ISSUE THREAD

**Issue by Jeremyye114** [wmchris/DellXPS15-9550-OSX#15]
I can‘t use the DisplayPort，i use the Typc-c to DisplayPort adaptor，but not working！

**Comment by wmchris** [comment]
the port is known to work. Check if you get a signal from within the BIOS. If yes: check in Step 7 "Fix HDMI Output" - its the same for DP.

**Comment by Jeremyye114** [comment]
@wmchris Thanks for your instructions,I've solved this problem.But when I use DisplayPort and HDMI output,the content of the two displays are the same,can you solve this problem?Or it's the problem of HD530 hardware?

**Comment by wmchris** [comment]
normally these two devices use different lanes, never tested by myself, so i have no personal experience with 3 displays. i only know of at least two people that a 3+ monitor setup is possible.

just remember, that you've a strict limit on processing power. so maybe reducing the resolution could help you switching from cloned to extended mode.
