### ISSUE TITLE
OC 0.7.1 vs 0.7.0

### ISSUE THREAD

**Issue by dmikhalsky** [wmchris/DellXPS15-9550-OSX#166]
If I want to install using debug versions of OC, shall I use 0.7.0 or 0.7.1?
There seems to be some confusion as it stated that BOOTx64.efi was updated to 0.7.0 (issue #153), but OC folder content is 0.7.1 (issue #156)
Given config.plist is updated to 0.7.1, I assume I should use 0.7.1, correct?

**Comment by golimpio** [comment]
`BOOTx64.efi` file from **0.7.1** is identical to the previous one in **0.7.0**, that's the reason git kept the previous one.

**Comment by dmikhalsky** [comment]
Crystal clear now. Thx.
