### ISSUE TITLE
Notes for macOS 12.0 (Monterey)

### ISSUE THREAD

**Issue by golimpio** [wmchris/DellXPS15-9550-OSX#167]
This is for keeping tracking of what has to be changed in order to upgrade to Monterey.

I've done it myself, the update was simple and it can be done through the normal macOS _Software Update_ (it takes a while though). 

On my first attempt (_Beta 3_), the system was constantly freezing, but as per @dnsdk comment, this seems to be an issue with `FakePCIID*`. Without `FakePCIID*` the system seems to be stable (for a beta version anyway).

###  Back to the upgrade:

In order to upgrade to Monterey, we just need a couple of changes, and that's because bluetooth can't be injected the same way it is in Big Sur, and `FakePCIID` is currently not compatible with Monterey:

- Replace `BrcmBluetoothInjector` kext by `BlueToolFixup` (**DO NOT** use `BrcmBluetoothInjector` for Monterey).
- Disable `FakePCIID*` (all `FakePCIID` related kexts)

For reference:

- https://github.com/acidanthera/bugtracker/issues/1669
- https://github.com/acidanthera/BrcmPatchRAM/pull/12

**Comment by golimpio** [comment]
To make it simple, here's the config bit for `BlueToolFixup` (`Kernel > Add`):

```
    <dict>
        <key>Arch</key>
        <string>x86_64</string>
        <key>BundlePath</key>
        <string>BlueToolFixup.kext</string>
        <key>Comment</key>
        <string></string>
        <key>Enabled</key>
        <true/>
        <key>ExecutablePath</key>
        <string>Contents/MacOS/BlueToolFixup</string>
        <key>MaxKernel</key>
        <string></string>
        <key>MinKernel</key>
        <string></string>
        <key>PlistPath</key>
        <string>Contents/Info.plist</string>
    </dict>
```

** Remember to remove `BrcmBluetoothInjector`

`BlueToolFixup` is part of `BrcmPatchRAM`, so just grab the kext from the official repository:

- https://github.com/acidanthera/BrcmPatchRAM

**Comment by dnsdk** [comment]
The freezes problem is FakePCIID

**Comment by golimpio** [comment]
> The freezes problem is FakePCIID

Thanks for letting me know, when I have a chance, I'll try it again without FakePCIID and see how it goes.

**Comment by golimpio** [comment]
Removing `FakePCIID` fixed the freezing issue.

<img width="698" alt="Screen Shot 2021-07-26 at 11 00 31 pm" src="https://user-images.githubusercontent.com/138681/126993417-667f52e2-d75a-4e73-b570-f65f951a67a4.png">

**Comment by Ruud-C** [comment]
Monterey beta is working for me as well after disabling FakePCIID, which is nice (with FakePCIID it crashed for me as well). Unfortunately as a consequence sound is not working anymore.

**Comment by golimpio** [comment]
> Monterey beta is working for me as well after disabling FakePCIID, which is nice (with FakePCIID it crashed for me as well). Unfortunately as a consequence sound is not working anymore.

I haven't tested beta 4 yet, but on beta 3, sound/mic were working fine here. I'm not sure if you're talking about HDMI audio (I haven't tested this one). 

Also, I didn't test if audio was still working after sleeping.

**Comment by golimpio** [comment]
About the freezing issue I've experienced before, it's still there unfortunately. I've tried to update my test SSD to beta 4 and it froze a couple of times already while browsing the internet and waiting for the beta 4 download.

`FakePCIID` was a main issue, but unfortunately for me, it wasn't the only one.

**Comment by Ruud-C** [comment]
> > Monterey beta is working for me as well after disabling FakePCIID, which is nice (with FakePCIID it crashed for me as well). Unfortunately as a consequence sound is not working anymore.
> 
> I haven't tested beta 4 yet, but on beta 3, sound/mic were working fine here. I'm not sure if you're talking about HDMI audio (I haven't tested this one).

I'm running beta 4. I meant built-in audio, i.e. not via HDMI (haven't tried that). If I open sound settings it says that there are no input or output devices.

What I did to install Monterey was get the latest version of the files here from GitHub, so the latest config.plist, Open Core, kexts etc. In config.plist I disabled `FakePCIID` and `BrcmBluetoothInjector` but did not add `BlueToolFixup` yet since I don't use bluetooth. I also added `itlwm` since wifi didn't work without it. Other than that I did not change anything, so I am surprised to see that audio is working for you and not for me.

My system is not freezing, it froze once with `FakePCIID` enabled after which I disabled it and it has been running fine ever since.

**Comment by nmhendriks75** [comment]
Notes on Monterey
I'm running Beta 4 on XPS9550 almost everything works after 

- Disable FakePCIID
- Disable FAKEPCID_Intel_HDMI_Audio
- Disable BrcmBluetoothInjector
- Enable BluetoolFixup

What does **not** work is

- External Monitor via HDMI port
    Solved that by using USB-C to HDMI Adapter
- Webcam sort of works but the image is really dark, not usable for online meetings

**Comment by Ruud-C** [comment]
@nmhendriks75 I had not disabled `FakePCIID_Intel_HDMI_Audio`, did that just now and now audio is working. Cool, thanks for the heads up

**Comment by golimpio** [comment]
> * Webcam sort of works but the image is really dark, not usable for online meetings

I couldn't notice the difference between Big Sur and Monterey, for me, the webcam image looks bad in both.

Have you notice any difference on Monterey? Or is it just as bad as it was in Big Sur?

**Comment by nmhendriks75** [comment]
Using a dualboot now (Big Sur and Monterey).

The webcam always worked great on Catalina and Big Sur(first image below).
On Monterey the image(below) is almost completly dark but when actualy using the cam you can see some movement).


<img width="438" alt="Webcam - BigSur" src="https://user-images.githubusercontent.com/67360170/127732766-90a63147-6564-45b6-aa32-74c55174cd83.png">
<img width="442" alt="Webcam - Monterey" src="https://user-images.githubusercontent.com/67360170/127732778-c398d00a-4119-4e9e-b76e-59b8bf89896a.png">

**Comment by golimpio** [comment]
> Using a dualboot now (Big Sur and Monterey).
> 
> The webcam always worked great on Catalina and Big Sur(first image below).
> On Monterey the image(below) is almost completly dark but when actualy using the cam you can see some movement).
> 

That's really bad. I don't have this issue in Monterey, the image is fine compared to your.

Both images are from Monterey (beta 4):

![Photo on 31-7-21 at 5 55 pm](https://user-images.githubusercontent.com/138681/127733223-c34eb442-e045-4eb1-98be-fb2e2e75486e.jpg)

<img width="512" alt="Screen Shot 2021-07-31 at 6 01 22 pm" src="https://user-images.githubusercontent.com/138681/127733357-bf3ecfa9-459f-4f07-85ea-b38cb2fbeeaa.png">

I no longer have Big Sur to compare, but I've tested the webcam on both before replacing Big Sur, the images from both systems were the same over here.

**Comment by golimpio** [comment]
I've updated to **OC 0.7.2** and the latest kexts, but I don't think there is anything relevant for this setup. Anyway, I've been using Monterey Beta 4 as my only OS and so far, it's fine, not bad for a beta.

A few things that I've noticed:

- Waking up from sleep isn't too stable, a couple of times macOS became too slow after sleep and one time there was no sound;
- Bluetooth isn't too bad, it works fine most of the time, but a couple of times it just turned off and wouldn't turn on until rebooting;
- I haven't experienced any camera issues so far, but as related a couple of comments above, it's not stable yet;
- The first time I've installed this Monterey, there was no sound, and then, after a few reboots, the sound was back, now, after upgrading OC and kexts, sound is gone again. I'll wait a bit longer to see if it comes back with the following reboots (like the last time).

It looks promising so far!

**Edit:** Sound is back and working again after a couple of reboots.

**Comment by aaronjrodrigues** [comment]
What does the Fake PCIID kext (or kexts) do? Like what function did they serve in Big Sur for it to be part of the kexts?

**Comment by golimpio** [comment]
> What does the Fake PCIID kext (or kexts) do? Like what function did they serve in Big Sur for it to be part of the kexts?

Someone else might be more helpful in answering your question, until then, have a look at the readme file for the `FakePCIID` project, it explains why this kext exists:

- https://github.com/RehabMan/OS-X-Fake-PCI-ID

Also, there are a few discussions about `FakePCIID` out there, for example:

- https://www.reddit.com/r/hackintosh/comments/77d94h/can_someone_explain_fakepciid_and_fakeid_to_me/

For this specific project, we rely on `FakePCIID` + `FakePCIID_Intel_HDMI_Audio.kext`, to provide HDMI audio support for our laptop, which is also better explained in the first link above (from RehabMan repository).

It seems that `AppleALC` added controller patch for 100 Series, and in theory we no longer need `FakePCIID_Intel_HDMI_Audio.kext`, but I don't have an HDMI audio device to test/confirm it. More here: #152

**Comment by golimpio** [comment]
I've been running Monterey Beta 5 for a while and it performs a lot better than Beta 4. Unfortunately it introduced some compatibility issues with some apps I have (i.e. Photoshop, DaisyDisk). On the good side, it fixed issues with Chrome, which used to freeze every single day in Beta 4.

**Comment by aaronjrodrigues** [comment]
> To make it simple, here's the config bit for `BlueToolFixup` (`Kernel > Add`):
> 
> ```
>     <dict>
>         <key>Arch</key>
>         <string>x86_64</string>
>         <key>BundlePath</key>
>         <string>BlueToolFixup.kext</string>
>         <key>Comment</key>
>         <string></string>
>         <key>Enabled</key>
>         <true/>
>         <key>ExecutablePath</key>
>         <string>Contents/MacOS/BlueToolFixup</string>
>         <key>MaxKernel</key>
>         <string></string>
>         <key>MinKernel</key>
>         <string></string>
>         <key>PlistPath</key>
>         <string>Contents/Info.plist</string>
>     </dict>
> ```
> 
> ** Remember to remove `BrcmBluetoothInjector`
> 
> `BlueToolFixup` is part of `BrcmPatchRAM`, so just grab the kext from the official repository:
> 
>     * https://github.com/acidanthera/BrcmPatchRAM

Is it necessary to add that config bit from your post

All I did was just remove the FakePCIID kexts, replaced the bluetooth kext and did an OC Snapshot. That should be okay, right?

**Comment by golimpio** [comment]
> 
> Is it necessary to add that config bit from your post
> 
> All I did was just remove the FakePCIID kexts, replaced the bluetooth kext and did an OC Snapshot. That should be okay, right?

**Edit**: Sorry, I missed the part of the `OC Snapshot`, I haven't done it myself, but I think you're right, it should work and you don't need the bit from my post.

(I removed part of my reply, since it wasn't related to what you've asked)

**Comment by aaronjrodrigues** [comment]
Anyway, I got monterey installed (With FakePCIID and the Fake PCIID for HDMI audio and can confirm that HDMI Display nor Audio works but isnt an issue for me as I barely use it)

**Comment by aaronjrodrigues** [comment]
Normal audio is working fine, bluetooth audio is also working fine upon replacing BrcmBluetoothInjector with BlueToolFixup.

**Comment by golimpio** [comment]
Starting beta 6 (21A5506j) tests. 

I've tried to install it via normal _Software Update_, but it didn't work for me. I had no issues during the installation, but when it finished, it got stuck after I've entered the filevault password: the progress bar (boot) only showed like 5% progress and then stayed there forever - at least a couple of hours before I rebooted it.

On the next reboot, I've entered in the recovery mode and ran _"Reinstall macOS 12 Beta"_, it automatically downloaded the latest beta and reinstalled it.

It took some time, but it was the easiest hackintosh installation I've ever done, I've just sat down and watched the whole installation process, the only thing I had to do was to enter the filevault password. This time it booted without any issues and everything went back to normal (so far).

**Comment by aaronjrodrigues** [comment]
Thats wierd, because it worked perfectly fine for me. I do not use FileVault though. I noticed that in the Software updates tab in System Preferences that after downloading it takes a while where it shows 30 minutes remaining but it takes longer than that after rebooting to update everything went very smooth for me.

**Comment by aaronjrodrigues** [comment]
Also, forgot to mention that when I  installed monterey a few days ago that the webcam also works perfectly fine. This beta has been really stable so far, hopefully it would continue this way for me.

**Comment by aaronjrodrigues** [comment]
I noticed that when I download files from the App Store, it downloads but gets stuck e.g 784.4MB/784.4MB and it doesent want to install. I am not sure if this is a Monterey issue however I was able to instal Safari extensions just fine in Big Sur.

**Comment by golimpio** [comment]
The last `Beta 7` update was a bit tricky to install, for what I've read, quite a few people were having issues as well.

The issue I was having was that when the system tried to update, it rebooted into a loop. Some people reported that they could install it successfully after temporarily changing the SMBIOS to `iMac17,1`, but I haven't tried it as it's not a good workaround IMO.

It seems that `OC 0.7.3` isn't compatible with this update and there is already a change in `0.7.4`  that solves the issue with the `Beta 7` update. I can confirm that in my case, using the trunk version of `OC 0.7.4` did the trick. 

After the `Beta 7` update is installed, the latest stable version (`OC 0.7.3`) can be used again to boot the system (the issue was with the install software only).

The change made in `OC 0.7.4` is described here ([Added large BaseSystem support in `AdviseFeatures`](https://github.com/acidanthera/OpenCorePkg/commit/1cb8490fd60f6b5f983d42e5bbf08e3d2d43d8f6)): 

- https://github.com/acidanthera/OpenCorePkg/commit/1cb8490fd60f6b5f983d42e5bbf08e3d2d43d8f6

**Comment by golimpio** [comment]
`Beta 8` (21A5534d) updated successfully. I'm using `OC 0.7.4` and I haven't tested it with the current stable version `0.7.3`.

**Comment by golimpio** [comment]
`Beta 9` (21A5543b) updated successfully. It needs the latest stable `OC 0.7.4`.

Some people have reported that external monitor wasn't working before _Beta 9_, but I couldn't verify it (**note:** these reports weren't for this laptop).

**Comment by golimpio** [comment]
`Beta 10` (21A5552a) update was successful as well.

**Comment by golimpio** [comment]
Almost there... The macOS Monterey version **12.0.1 RC (21A558)** was updated successfully.

**Comment by golimpio** [comment]
I've started testing the relatively new kext for the SD card reader: [RealtekCardReader](https://github.com/0xFireWolf/RealtekCardReader) (so far it seems to work well).

[RealtekCardReaderFriend](https://github.com/0xFireWolf/RealtekCardReaderFriend/) was also installed, as it seems to be required for macOS to recognise it as a built-in card reader device.

<img width="712" alt="Screen Shot 2021-10-20 at 10 09 44 pm" src="https://user-images.githubusercontent.com/138681/138082383-f892acb7-69d6-4aa0-ab4e-bad379638182.png">

**Comment by krim404** [comment]
is the card reader still draining the battery very fast?

**Comment by golimpio** [comment]
> is the card reader still draining the battery very fast?

I haven't tested it. 

TBH, the battery on my laptop doesn't last long nowadays and I use it always plugged.  Until this week, I had the SD card disabled in BIOS, so this is actually the first time I'm using it.

I've unplugged the laptop from the power for a simple test and I can see in coconutBattery that it's draining fast, it went from 98% to 91% in about 5 minutes (display is ~ 90% bright).  Unfortunately I don't have the numbers to compare with the sd-card disabled, but it was already draining fast before enabling the card.

Although I didn't have any major issues so far, I'm still not confident that this new kext is stable enough, if I have a sd-card inserted, the coconutBattery app won't start and it will crash, which is odd but I hope it's just an isolated issue.

I'll keep using it and will see if it's at least stable to read/write to sd cards.

**Comment by golimpio** [comment]
Another RC installed without any issues: **12.0.1 (21A559)**.

At this point I think it's safe to say that Monterey works well with this laptop. There are more tests to do though, like external monitors. Hopefully I might be able to test it soon.

I'm waiting to the final release before sharing my OC config. But if anyone need it, just ask.

**Comment by aaronjrodrigues** [comment]
Is it just me but I am trying to update to 0.7.4 from 0.7.1 to update to Monterey but it just doesnt work.

After replacing boot64, opencore.efi and openruntime my gui for the boot selector goes and when booting into macos i get the ocb error.

**Comment by golimpio** [comment]
> Is it just me but I am trying to update to 0.7.4 from 0.7.1 to update to Monterey but it just doesnt work.
> 

OC **0.7.4** is working fine here.  I've attached my OC folder:
- [OC.zip](https://github.com/krim404/DellXPS15-9550-OSX/files/7421122/OC.zip)

**Comment by golimpio** [comment]
> After replacing boot64, opencore.efi and openruntime my gui for the boot selector goes and when booting into macos i get the ocb error.

About the GUI, have you updated `OpenCanopy.efi`? 

It usually has to be the same version from the OC you're running as a general rule, but sometimes they don't change anything, in that case, it doesn't make any difference, but when there are changes it might break your GUI if you don't use the same version.

**Comment by aaronjrodrigues** [comment]
> > After replacing boot64, opencore.efi and openruntime my gui for the boot selector goes and when booting into macos i get the ocb error.
> 
> About the GUI, have you updated `OpenCanopy.efi`?
> 
> It usually has to be the same version from the OC you're running as a general rule, but sometimes they don't change anything, in that case, it doesn't make any difference, but when there are changes it might break your GUI if you don't use the same version.

I had tried doing that when someone in the hackintosh discord recommended me to, But it didn't get fixed unfortunately.

**Comment by aaronjrodrigues** [comment]
> > Is it just me but I am trying to update to 0.7.4 from 0.7.1 to update to Monterey but it just doesnt work.
> 
> OC **0.7.4** is working fine here. I've attached my OC folder:
> 
>     * [OC.zip](https://github.com/krim404/DellXPS15-9550-OSX/files/7421122/OC.zip)

After using your EFI and putting in my iMessage serials and stuff  and I was able to successfully able to update to Monterey - Thank you so much, I also love the theme that you have in there.

**Comment by krim404** [comment]
@golimpio is it okay for you if i create the new branch based on your files?

**Comment by golimpio** [comment]
@krim404 sorry, I only saw your msg now.

I noticed that the 12 branch is created already, thanks! 
Can I close this issue? Did it work fine or did you need to do some modifications?

**Comment by krim404** [comment]
it worked out of the box for me. so we can close this :)
