### ISSUE TITLE
Requesting the sources for the content of the ACPI, Drivers and Kexts folders

### ISSUE THREAD

**Issue by aaronjrodrigues** [wmchris/DellXPS15-9550-OSX#168]
I would like to contribute to this repo but would also need to know the sources of the files from the ACPI, Drivers and Kexts so I can know where to get the updated version.

Any help would be appreciated :)

**Comment by golimpio** [comment]
ACPI files can be opened/edited/compiled with `MaciASL`, dortania's guides cover pretty much everything:

- https://dortania.github.io/Getting-Started-With-ACPI/Manual/compile.html#macos
- https://dortania.github.io/Getting-Started-With-ACPI/#a-quick-explainer-on-acpi

These ACPI files were extracted from this laptop (XPS15 9550), and customised for it. So I'm not sure what you meant by _"get the updated version"_ in this case, but anything else, like drivers and kexts you'll find in github or can easily google for them.

Guide and shortcut to most of repositories assets are also covered by dortania:

- https://dortania.github.io/OpenCore-Install-Guide/ktext.html#firmware-drivers

Most of the source code can be found in the acidenthera's repositories:

- https://github.com/acidanthera

**Comment by golimpio** [comment]
Also, if you already have macOS installed for XPS15, `Hackintool` is a good app to install, it will give you the link to most of the kexts you have installed and keep you informed about updates:

- https://github.com/headkaze/Hackintool

**Comment by golimpio** [comment]
All the history, and information about some decisions and kexts used here can be found at InsanelyMac forum:

- https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation

**Comment by aaronjrodrigues** [comment]
> ACPI files can be opened/edited/compiled with `MaciASL`, dortania's guides cover pretty much everything:
> 
> * https://dortania.github.io/Getting-Started-With-ACPI/Manual/compile.html#macos
> * https://dortania.github.io/Getting-Started-With-ACPI/#a-quick-explainer-on-acpi
> 
> These ACPI files were extracted from this laptop (XPS15 9550), and customised for it. So I'm not sure what you meant by _"get the updated version"_ in this case, but anything else, like drivers and kexts you'll find in github or can easily google for them.
> 
> Guide and shortcut to most of repositories assets are also covered by dortania:
> 
> * https://dortania.github.io/OpenCore-Install-Guide/ktext.html#firmware-drivers
> 
> Most of the source code can be found in the acidenthera's repositories:
> 
> * https://github.com/acidanthera

Oh ok, I did not know they were customised and thought they were just generic ACPI files. Thank you for responding.

**Comment by aaronjrodrigues** [comment]
> Also, if you already have macOS installed for XPS15, `Hackintool` is a good app to install, it will give you the link to most of the kexts you have installed and keep you informed about updates:
> 
> * https://github.com/headkaze/Hackintool

Thank you so much for linking me to this, It looks really useful for me.

**Comment by aaronjrodrigues** [comment]
> All the history, and information about some decisions and kexts used here can be found at InsanelyMac forum:
> 
> * https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation

Thank you very much, I will have a look at this.

**Comment by golimpio** [comment]
> 
> Oh ok, I did not know they were customised and thought they were just generic ACPI files. Thank you for responding.

Sorry, my bad, they are customised, but they are originally from generic ones (like you said). 

Anyway, you can still open the `.aml` files from this repository with `MaciASL` and access the source code. Then, if this is something you're interested in, you could compare them with the generic/prebuilt ones to check what was changed. I can't guide you on this one, because it wasn't me that did all the hard work.

You can find a few prebuilt ssdt here:

- https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-prebuilt.html#laptop-skylake-and-kaby-lake

In the past we used to dump the DSDT from this laptop and do the changes, but it has been a while since this is no longer necessary.
