### ISSUE TITLE
Sleep mode issues

### ISSUE THREAD

**Issue by aaronjrodrigues** [wmchris/DellXPS15-9550-OSX#169]
Does anyone have issues where when you leave your laptop unattended for some time and the screen turns off (I think it goes into sleep mode) and when you wake it up again it sometimes just stays as a black screen even though there is a light by the power button and clicking the trackpad doesn't even wake the screen up. I had to always force restart my PC using the power button to fix it. This issue only happens some times and not all the time.

Is anyone else having this issue and/or does anyone know how to fix this

I also wanted to know how I can make the laptop turn its screen off from sleep mode using the power button itself instead of clicking the power button and then waking the screen using the trackpad (when the above issue does not happen).

Any help would be appreciated!

**Comment by golimpio** [comment]
Just to confirm, did you run: `disablehibernate.sh`? 

- https://github.com/wmchris/DellXPS15-9550-OSX/tree/11.0/11.0/Post-Install/Additional%20Steps/Hibernation#hibernation-disabler

More details here:

- https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html

**Comment by golimpio** [comment]
> I also wanted to know how I can make the laptop turn its screen off from sleep mode using the power button itself instead of clicking the power button and then waking the screen using the trackpad (when the above issue does not happen).
> 
> Any help would be appreciated!

Have you tried `darkwake`?

More information here:

- https://dortania.github.io/OpenCore-Post-Install/usb/misc/keyboard.html
