### ISSUE TITLE
HDMI Video Out: AppleGraphicsControl.kext fehlt

### ISSUE THREAD

**Issue by MTechDE** [wmchris/DellXPS15-9550-OSX#17]
Die .kext Datei welche für den HDMI Video Output benötigt wird, ist nach der Installation aller optionalen kext Dateien nicht vorhanden.

**Comment by wmchris** [comment]
das ist eine Kext von Apple selbst.
/System/Library/Extensions/AppleGraphicsControl.kext

**Comment by MTechDE** [comment]
Genau das meinte ich ja. Die Kext Datei ist nicht vorhanden.

**Comment by wmchris** [comment]
dann ist bei der Installation was schiefgelaufen. Das ist eine Standarddatei ohne die Mac OS meines wissens nicht bootet.

**Comment by MTechDE** [comment]
Ich habe die Installation ein weiteres Mal wiederholt. Die Datei ist nicht da.

**Comment by wmchris** [comment]
auf 4 macs gerade geprüft - kext ist im normalfall vorhanden. Hat nichts mit meinem Tutorial zu tun. ggf Google nutzen / neuen USB stick erstellen / neues Image runterladen.
