### ISSUE TITLE
Status for Big Sur 11.6

### ISSUE THREAD

**Issue by lamhoangtung** [wmchris/DellXPS15-9550-OSX#171]
Hi. Have anyone update via OTA to Big Sur 11.6 ?

Would love to have some info on this. Thanks for checking by

**Comment by aaronjrodrigues** [comment]
Yes, I have been able to update to 11.6 without any issues whatsoever.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lamhoangtung** [comment]
Thanks @aaronjrodrigues. I upgraded to 11.6 without any issues as well.
