### ISSUE TITLE
Unable to connect to the internet suddenly

### ISSUE THREAD

**Issue by aaronjrodrigues** [wmchris/DellXPS15-9550-OSX#172]
Hey, so basically I was using my XPS normally until suddenly WiFi and Bluetooth just stopped working. I tried restarting, tried resetting nvram, I also tried using the wireless diagnostics but none of them helped fix it. I tried even downloading the efi from the github again and tried booting it but the issue wasn't fixed.

Could someone please help me :)

**Comment by lamhoangtung** [comment]
I got this exact problem a while ago. I can help

Can you try to boot into another OS, like Ubuntu Live USB and verify that the wifi card are still being detected by Ubuntu ?

**Comment by aaronjrodrigues** [comment]
Hey, I've booted into windows and installed my driver's by getting them downloaded on another device. Usually I need to install the drivers myself as the windows ones don't work but usually after installing them, the internet is supposed to work but it doesn't. Flicking the switch to turn on WiFi doesn't do anything (just like in macos) running the troubleshooter says that the wireless capability is turned off.

-------- Original Message --------

**Comment by aaronjrodrigues** [comment]
> I got this exact problem a while ago. I can help
> 
> Can you try to boot into another OS, like Ubuntu Live USB and verify that the wifi card are still being detected by Ubuntu ?

After installing the drivers on windows it recognizes that there is my dell wireless 1830 but when it gives the same effects as in macos as in I can't turn on WiFi.

**Comment by krim404** [comment]
well it sounds like a hardware problem. nothing we can fix here.

**Comment by aaronjrodrigues** [comment]
> well it sounds like a hardware problem. nothing we can fix here.

Hey, I don't this this is a hardware issue as I have heard similar stories about this but I personally haven't found a solution yet. Please keep this open as I'm waiting for a response from @lamhoangtung

**Comment by ghost** [comment]
@aaronjrodrigues Hello there. Before you rule it is a hardware issue, do the following:
Boot in to your BIOS settings by pressing F2. Then go down the the +Wireless tab. Make sure the following are enabled. IF THEY ARE, TURN ON AND OFF, AND BACK ON again.
Wireless Switch
- [x] WLAN
- [x] Bluetooth

Wireless Device Enable
- [x] WLAN
- [x] Bluetooth.

Last time I had an issue with Bluetooth and this worked. Try it.

**Comment by aaronjrodrigues** [comment]
I tried doing this but no avail, hoping that @lamhoangtung would have a solution that will hopefully work :)

Thank you though.

**Comment by aaronjrodrigues** [comment]
> I got this exact problem a while ago. I can help
> 
> Can you try to boot into another OS, like Ubuntu Live USB and verify that the wifi card are still being detected by Ubuntu ?

I booted in a manjaro usb as I couldn't download Ubuntu and it looks like it detects that this pc is supposed to have WiFi functionality (not sure how to check if it detects the WiFi card but it shows a WiFi panel in the settings) but it can't scan for any visible networks.

**Comment by ghost** [comment]
> > I got this exact problem a while ago. I can help
> > Can you try to boot into another OS, like Ubuntu Live USB and verify that the wifi card are still being detected by Ubuntu ?
> 
> I booted in a manjaro usb as I couldn't download Ubuntu and it looks like it detects that this pc is supposed to have WiFi functionality (not sure how to check if it detects the WiFi card but it shows a WiFi panel in the settings) but it can't scan for any visible networks.
If you are in the usb live environment. Then type the following command in Terminal:
`lsmod` 
Is there an output for brcmfmac?   which is the module that should be loaded for the kernel to get WiFi to work . If there is a brcmfmac module loaded,  and the `ip a` command does not show wlp3s0 or wlan then you might have hardware issues. Since you have already checked this on Windows, MacOs, Linux.

**Comment by lamhoangtung** [comment]
Hi @aaronjrodrigues. Sorry for the late rely. I even went out to buy a new Wifi card for my machine just to know that it was a simple fix.

So at the top right of the laptop, you have a function button to turn off both Wifi and Bluetooth at a hardware level, it's look like this

<img width="655" alt="Screen Shot 2021-11-15 at 08 19 59" src="https://user-images.githubusercontent.com/26834698/141707903-945d3e09-659b-461e-bc42-ab07f8fd14d6.png">

In MacOS, this button was mapped to something else and not suppose to be run normally to disable wifi and bluetooth like on Windows did. But somehow it might fail and activate itself to unexpectedly turn off stuff.

Now to turn it back on. Reboot your machine, and press F12 repeatedly until you see this screen
![IMG_0711](https://user-images.githubusercontent.com/26834698/141708613-8ee31b51-1a81-4719-8f74-c5a42c154d84.jpg)

Go to Diagnostics. Skip all the test by pressing ESC and answer Yes/No accordingly. Then you should arrive in a screen like this:

![IMG_0712](https://user-images.githubusercontent.com/26834698/141708734-c00c93a8-37d1-44b4-ab29-f92613d5d358.jpg)

In the Configuration tab, you will see that Wifi and Bluetooth are disconnected as the tool report (sorry for not taking an exmaple screenshot, but you don't need to care that much)

Now. Press the PrtScr button (if your machine on Fn lock) or Fn + PrtScr to reconnect wifi and bluetooth. A pop up will show up to let you know it was connected:

![IMG_0713](https://user-images.githubusercontent.com/26834698/141708900-195cd79d-8d56-421d-83a5-c01f649b9296.jpg)

And that's it, just hit Exit in the top right corner and boot back to MacOS. Everything should work properly.

Hope this can help!

**Comment by aaronjrodrigues** [comment]
> Hi @aaronjrodrigues. Sorry for the late rely. I even went out to buy a new Wifi card for my machine just to know that it was a simple fix.
> 
> So at the top right of the laptop, you have a function button to turn off both Wifi and Bluetooth at a hardware level, it's look like this
> 
> <img alt="Screen Shot 2021-11-15 at 08 19 59" width="655" src="https://user-images.githubusercontent.com/26834698/141707903-945d3e09-659b-461e-bc42-ab07f8fd14d6.png">
> 
> In MacOS, this button was mapped to something else and not suppose to be run normally to disable wifi and bluetooth like on Windows did. But somehow it might fail and activate itself to unexpectedly turn off stuff.
> 
> Now to turn it back on. Reboot your machine, and press F12 repeatedly until you see this screen ![IMG_0711](https://user-images.githubusercontent.com/26834698/141708613-8ee31b51-1a81-4719-8f74-c5a42c154d84.jpg)
> 
> Go to Diagnostics. Skip all the test by pressing ESC and answer Yes/No accordingly. Then you should arrive in a screen like this:
> 
> ![IMG_0712](https://user-images.githubusercontent.com/26834698/141708734-c00c93a8-37d1-44b4-ab29-f92613d5d358.jpg)
> 
> In the Configuration tab, you will see that Wifi and Bluetooth are disconnected as the tool report (sorry for not taking an exmaple screenshot, but you don't need to care that much)
> 
> Now. Press the PrtScr button (if your machine on Fn lock) or Fn + PrtScr to reconnect wifi and bluetooth. A pop up will show up to let you know it was connected:
> 
> ![IMG_0713](https://user-images.githubusercontent.com/26834698/141708900-195cd79d-8d56-421d-83a5-c01f649b9296.jpg)
> 
> And that's it, just hit Exit in the top right corner and boot back to MacOS. Everything should work properly.
> 
> Hope this can help!

Oh my god thank you so much it worked!!

**Comment by lamhoangtung** [comment]
Happy to help ;)

**Comment by ghost** [comment]
@aaronjrodrigues  Sorry for me assuming you actually knew that your laptop has this setting. Honestly you dont need to go to into diagnostics. You can simply reboot your laptop and while the Dell logo is showing, just press Fn+PtrScr. Then the wifi switch will be turn on.
