### ISSUE TITLE
Bluetooth headphones sound quality

### ISSUE THREAD

**Issue by golimpio** [wmchris/DellXPS15-9550-OSX#173]
I'm wondering how is the bluetooth connection quality for headphones on your setup. I didn't have any bluetooth headphone until recently, so it's something new to me. When I've plugged it, I noticed that the interference is quite annoying to listen to music.

E.g. every couple of seconds (or few seconds) the sound will fail for an instant (miliseconds), like a glitch or something similar.

I'm not sure if this is specific to my earphone (Airpods), or to my setup. Anyway, the Airpods work perfect on my mobile device, so it's not an issue with it.

Although this isn't necessarily an issue (I'll close this soon), I appreciate if anyone has any thoughts to share.

Thanks!

**Comment by lamhoangtung** [comment]
I don't have good experience with my Airpods Pro either. They auto disconnect and reconnect every 30 mins. The reconnection tooks about 5 seconds and it's so annoying. Other aspect are fine though

**Comment by krim404** [comment]
I used Bose QC35 and Beats Studio3 and didnt have any quality issues. Used them daily.

**Comment by golimpio** [comment]
Thank you @krim404 and @lamhoangtung for the feedback, it seems that we all experience different behaviour from our bluetooth headphones :)

It's not a big deal for me, this still one of the best hackintoshes I had. I guess the airpods pro might have issue with hackintoshes. But I'm able to do a zoom call with it, so for basic use, it's good enough.

I'm going to close this, so we don't have unnecessary issues opened.

Cheers!
