### ISSUE TITLE
Broken link to file repository

### ISSUE THREAD

**Issue by Ole-Brum** [wmchris/DellXPS15-9550-OSX#177]
Install macOS Monterey.

In the section Locations and required Files, there is a link named This repository.
This link "https://codeload.github.com/krim404/DellXPS15-9550-OSX/zip/1112.0.0" gives a 404 error. 
Any change this can be fixed ?

**Comment by golimpio** [comment]
Link is fixed, it's now pointing to: [https://github.com/krim404/DellXPS15-9550-OSX/archive/refs/heads/12.0.zip](https://github.com/krim404/DellXPS15-9550-OSX/archive/refs/heads/12.0.zip)
