### ISSUE TITLE
Did you update opencore 0.7.8?

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#179]
i have a problem when computer boot

**Comment by ghsssss** [comment]
<img width="478" alt="WechatIMG4" src="https://user-images.githubusercontent.com/25170955/153842663-bdf52f69-e402-4757-894d-ac8e75f9782b.png">

**Comment by ghsssss** [comment]
Enter the system normally, but this will appear after the startup logo

**Comment by golimpio** [comment]
I run macOS 12.2.1 with OC 0.7.8, plus the latest kexts and I haven't seen this issue.

You'll have to fix your `config.plist` file though, because a few things has changed since 0.7.4 and it will display error messages, usually before the OC menu.

Have you ran `ocvalidate` to check if your `config.plist` has errors?

If you've downloaded OpenCore from their website, it comes with a tool called `ocvalidate` inside.  For OC 0.7.8, it should be in the following folder: 

* `.../OpenCore-0.7.8-RELEASE/Utilities/ocvalidate/ocvalidate`

From the command line, run it passing your `config.plist` as a parameter, for example, if your `config.pllist` has no errors, you should see:

```
> ./ocvalidate /Volumes/EFI/EFI/OC/config.plist

Completed validating /Volumes/EFI/EFI/OC/config.plist in 1 ms. No issues found.
```

**Comment by golimpio** [comment]
I've attached my `config.plist` for reference only, it's updated for _OC 0.7.8_:

[config.plist.zip](https://github.com/krim404/DellXPS15-9550-OSX/files/8059905/config.plist.zip)

**BE CAREFUL**, my `config.plist` is missing the patch for Hynix NVMe drives.  For _OC > 0.7.4_, I think that one of the things that has to be changed is the entry for this patch.  You'll get error messages if you simply add the patch without changing it.

**Comment by ghsssss** [comment]
i found 3 trouble on cofig 

Booter->Patch[0]->Identifier contains illegal character!
Booter->Patch[1]->Identifier contains illegal character!
CheckBooter returns 2 errors!

Misc->BlessOverride: \EFI\Microsoft\Boot\bootmgfw.efi is redundant!
CheckMisc returns 1 error!

**Comment by ghsssss** [comment]
cound you help me to fix it?

**Comment by ghsssss** [comment]
this is my confi
[config.plist.zip](https://github.com/krim404/DellXPS15-9550-OSX/files/8069463/config.plist.zip)
g

**Comment by ghsssss** [comment]
The first two errors I have solved by way of deletion, the third doesn‘t know how to solve, at the same time, the startup error has not disappeared

**Comment by golimpio** [comment]
About the 3rd error, you shouldn't need this line, since OpenCore 0.5.9, it no longer needs to be specified. OC will pick up the windows entry automatically.

Here your `config.plist`, it should be fixed:
[config.plist.txt](https://github.com/krim404/DellXPS15-9550-OSX/files/8070180/config.plist.txt)

**Comment by golimpio** [comment]
But I don't think this line is causing the issue you are having.  Unfortunately I don't know what is causing it, sorry.

**Comment by golimpio** [comment]
@krim404 about the patch for Hynix NVMe drives, should it be in `Kernel > Patch`, instead of `Booter > Patch` ?

**Comment by golimpio** [comment]
@ghsssss you might try to change `DisconnectHda` to `true` (instead of `false`), but I'm not sure if this will cause audio issues.  It might be worth testing it.

**Comment by golimpio** [comment]
I'm reopening this temporarily, so @krim404 has a chance to check the patch for Hynix.

**Comment by ghsssss** [comment]
@golimpio The problem remains

**Comment by golimpio** [comment]
sorry @ghsssss, I'm out of ideas.

**Comment by ghsssss** [comment]
@golimpio Thank you for your time on my problem. I'll try to reinstall the system in the future.

**Comment by dkkyeremateng** [comment]
> I've attached my `config.plist` for reference only, it's updated for _OC 0.7.8_:
> 
> [config.plist.zip](https://github.com/krim404/DellXPS15-9550-OSX/files/8059905/config.plist.zip)
> 
> **BE CAREFUL**, my `config.plist` is missing the patch for Hynix NVMe drives. For _OC > 0.7.4_, I think that one of the things that has to be changed is the entry for this patch. You'll get error messages if you simply add the patch without changing it.

I'm getting a black screen after sleep with I use this config. Any help?

**Comment by QuantumFluctuator** [comment]
> > I've attached my `config.plist` for reference only, it's updated for _OC 0.7.8_:
> > [config.plist.zip](https://github.com/krim404/DellXPS15-9550-OSX/files/8059905/config.plist.zip)
> > **BE CAREFUL**, my `config.plist` is missing the patch for Hynix NVMe drives. For _OC > 0.7.4_, I think that one of the things that has to be changed is the entry for this patch. You'll get error messages if you simply add the patch without changing it.
> 
> I'm getting a black screen after sleep with I use this config. Any help?

Did you run the post install script to disable sleep after installation?

**Comment by golimpio** [comment]
> > I've attached my `config.plist` for reference only, it's updated for _OC 0.7.8_:
> > [config.plist.zip](https://github.com/krim404/DellXPS15-9550-OSX/files/8059905/config.plist.zip)
> > **BE CAREFUL**, my `config.plist` is missing the patch for Hynix NVMe drives. For _OC > 0.7.4_, I think that one of the things that has to be changed is the entry for this patch. You'll get error messages if you simply add the patch without changing it.
> 
> I'm getting a black screen after sleep with I use this config. Any help?

Please, use the official config. The one attached to this issue isn't stable and it's less tested.

Also, check which `ig-platform-id` you are using, the following should be more stable:

```
      <key>AAPL,ig-platform-id</key>                                                                                                                                                
      <data>AAAWGQ==</data>
```

The ones for "Intel Iris Graphics 540" will cause the black screen after sleep.

**Comment by ghsssss** [comment]
@golimpio reset nvram can solve the bug
