### ISSUE TITLE
can not boot

### ISSUE THREAD

**Issue by xiaolongsc** [wmchris/DellXPS15-9550-OSX#18]
![img_0358](https://cloud.githubusercontent.com/assets/27112232/24834012/fedc46e0-1d0b-11e7-8e77-107e14ca9bd2.PNG)
xps15 9550 i7 6700hq 16g 4k

**Comment by wmchris** [comment]
issues like this require more debugging than just a screenshot. please post it here:
http://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-sierra-10122-quick-installation
