### ISSUE TITLE
I replaced my sk hyix 32gb ssd with a 256gb ssd and noticed boot times are actually considerably slower on the new ssd than on the sk Hynix, is there any way to restore the performance?

### ISSUE THREAD

**Issue by aaronjrodrigues** [wmchris/DellXPS15-9550-OSX#180]
I was loving macOS on that ssd but the storage was an issue so I replaced it with a larger ssd but performance is kinda worse than the sk Hynix but better than a hard drive. Any way to fix it?

**Comment by krim404** [comment]
well probably you exchanged a high speed ssd with a low speed ssd.
