### ISSUE TITLE
"Device Timed Out" error in Sidecar

### ISSUE THREAD

**Issue by Bamboo6** [wmchris/DellXPS15-9550-OSX#181]
This error occurs with a wireless connection in sidecar
![Device Timed Out](https://user-images.githubusercontent.com/31620080/156911243-969f8397-044b-4483-bce9-43dbc94f6601.png)

**Comment by krim404** [comment]
please set your language to english, as i dont understand this and as it is a screenshot i cannot type it in a translator either. i close it as long as more information will be delivered

**Comment by Bamboo6** [comment]
I'm sorry. I have updated the screenshot to English now. @krim404
