### ISSUE TITLE
Suggestions on which KEXTs to move to L/E

### ISSUE THREAD

**Issue by KYBOSH-san** [wmchris/DellXPS15-9550-OSX#183]
Can anyone offer suggestions on which kexts are safe and beneficial to move from the EFI/OC/kexts folder + the config.plist and into the Library/Extension folder?

And which ones should be left alone?  The tutorial mentions doing it as an option but offered no clue which might be a good candidate.

Thank you in advance

**Comment by golimpio** [comment]
The mention for moving kexts to S/L/E or L/E is probably something from the old Clover tutorial, this isn't the correct approach for OpenCore, we should keep the kexts in OC/Kexts:

- https://dortania.github.io/OpenCore-Install-Guide/clover-conversion/#removing-kexts-from-macos-s-l-e-and-l-e

**Comment by KYBOSH-san** [comment]
Thank you again for that @golimpio.
Since this guide is specifically for Monterey on the 9550 via OpenCore should we try to make it more current and accurate?
I'll be happy to write a few paragraphs for future visitors as I am just tideying my install up and its fresh on my mind.

**Comment by golimpio** [comment]
I'll let @krim404 reply this one, since he have written pretty much everything here :)

**Comment by ghost** [comment]
`sudo cp -r ./12.0/Post-Install/LE-Kexts/* /Library/Extensions/
`
This above should be removed from the 12.0 tutorial as well
