### ISSUE TITLE
AirDrop doesn't work on 12 but works perfect on 11

### ISSUE THREAD

**Issue by dkkyeremateng** [wmchris/DellXPS15-9550-OSX#187]
It can't send or receive data.

**Comment by krim404** [comment]
cant confirm, works well for me on two systems.

**Comment by dkkyeremateng** [comment]
> cant confirm, works well for me on two systems.

I can send items to an iPhone and a Mac but my device (Hackinstosh) is not discovered by other devices so it can't receive data.

**Comment by krim404** [comment]
as this is a feature which is highly dependent on your setup, i can only tell you to take a look on reddit and insanelymac for a solution. as it is working on both my 9550 machines very well and as you wrote you can send data but it is simply not found by the other devices - it is possibly a misconfiguration.

 if you find the solution, it would be nice to post it here in case someone else has similar problems.
