### ISSUE TITLE
Suggest update VoodooPS2Controller

### ISSUE THREAD

**Issue by ii404msn** [wmchris/DellXPS15-9550-OSX#2]
like   [https://github.com/syscl/OS-X-Voodoo-PS2-Controller](https://github.com/syscl/OS-X-Voodoo-PS2-Controller)

**Comment by wmchris** [comment]
syscls fork doesnt work with my setup. Destroyed all multitouch functionality.

**Comment by wmchris** [comment]
got updated a few days ago with a modified version. it now works.
