### ISSUE TITLE
No new boot option to continue the install

### ISSUE THREAD

**Issue by arshcaria** [wmchris/DellXPS15-9550-OSX#20]
I made a 10.12.4 usb installer using your clover files. I successfully booted from the usb key, partitioned the disk and started the installation. But after the installation progress bar finished and the laptop rebooted into clover, there was no new boot option to continue (or finish) the installation. The old boot option for installing from usb was still there. But when I booted using this one, I have to partition/install the whole process again. After that, there was still no new boot option in clover.

Just like what you said in step2 of the installation guide

> After the first reboot you should see a new boot option inside clover, which is highlighted by default. Just press enter. If you only see one, then something went wrong.

Any idea about this?

Thanks.

**Comment by wmchris** [comment]
Step 7, Issue 2 - Model Name Error OR clover doesnt boot

**Comment by arshcaria** [comment]
Thanks for your reply.
If I have understood the guide correctly, issue 2 of step7 is for when the installation has completed and can boot from usb (but cannot boot without usb).
But in my case, after the first reboot of the installation, there is no new boot option from the usb clover to continue the installation. There is only the old option for starting the installation from scratch.

**Comment by wmchris** [comment]
its the same fix.

**Comment by arshcaria** [comment]
Thank you. That might be caused by the usb stick since I created it using VMware running OSX. I will try recreating it using a Mac.

**Comment by Piping** [comment]
hi, I had the same issues. Did you solve it? how did you solve it? I couldn't find the boot option during the secondary stage of installing macOS. @arshcaria

**Comment by arshcaria** [comment]
How did you create the usb installer? I tried create ut using a real Mac (instead of a virtual machine) and then it worked.

**Comment by Piping** [comment]
@arshcaria I created a hard disk partition with in real mac, and boot with a usb stick.
I restore the system from Time Machine and upgrade from macOS install and then I can see the second boot stage option. 

Still No luck on the original approach.
