### ISSUE TITLE
Brightness level cannot be changed (FHD 9550)

### ISSUE THREAD

**Issue by arshcaria** [wmchris/DellXPS15-9550-OSX#21]
I installed 10.12.2 on my FHD 9550. Almost everything works as expected except that the brightness cannot be changed using keyboard. After pressing Fn F11/F12, there is no brightness indicating bar and the brightness does not change.  (while volume change works with Fn F1/F2/F3)

Before applying Step4 of the guide, the brightness can be changed. After applying Step4, then I cannot. I don't know which kext or what line in the config.plist has caused the issue. 

Do you have any clue on this?

Thank you!

**Comment by wmchris** [comment]
The repo is preconfigured for the UHD display. See:
https://github.com/wmchris/DellXPS15-9550-OSX/tree/master/Additional/PatchAppleBacklight_v2

**Comment by Piping** [comment]
@arshcaria use Intel-Backlight.kext and install an app called brightness by bergdesign.
It works.
