### ISSUE TITLE
Dell adaptor DA200 VGA/HDMI not Working

### ISSUE THREAD

**Issue by pjor94** [wmchris/DellXPS15-9550-OSX#22]
Ethernet and usb is working fine but vga and HDMI dosent work

**Comment by wmchris** [comment]
try https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/Tutorial_10.12_Step7.md, First entry: "HDMI Video-Out Fix for iMac7,1 or MBP13,3", please report back.
