### ISSUE TITLE
No New boot option to continue the install with 4K Sector Enabled

### ISSUE THREAD

**Issue by Piping** [wmchris/DellXPS15-9550-OSX#23]
HI, I enabled the 4k Sector on my toshiba ssd.

And after format the drive, I will able to install from installer.

However, After the reboot, the next stage boot option doesnt appear. 

Do you have any idea why the drive doesnt show up? Is it something related with 4K sector or clover doesnt read 4K sector boot partition?

**Comment by wmchris** [comment]
Duplicated. See #20
