### ISSUE TITLE
Can't check if my drive is comaptible 4k

### ISSUE THREAD

**Issue by Zirconiumirish** [wmchris/DellXPS15-9550-OSX#25]
I follow your guide for to convert in 4k and instll everything on ubuntu but when i used the command an specified my drive it told me "unable to detect device type" can't find a solution thats a toshiba nvme drive

Thanks for your help

**Comment by wmchris** [comment]
Toshiba are all compatible. Its possible your drive is malfunction or your drive is newer than the installed smart tools. there are multiple way to format in 4k mode, try google for a full list or ask the developer of the tool which tells you the error message.
