### ISSUE TITLE
Add the number of pages till first suitable block

### ISSUE THREAD

**Issue by danielsogl** [wmchris/DellXPS15-9550-OSX#27]
Hey,

ich habe leider ein kleines Verständnisprobleme seit dem Update deines Guides.

Speziell hiermit: https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/Additional/slide_calc.md

"you need a decent amount of pages to boot. Look in your memmap for the first Available block with enough pages."

Was meinst du mit "with enough pages"? Es gibt Blöcke mit 1 bis 1000 Blöcken.

Wäre super, wenn du das genauer erklären könntest.

**Comment by wmchris** [comment]
anleitung wurde erweitert
