### ISSUE TITLE
Everything still working with no changes on 1.2.25

### ISSUE THREAD

**Issue by shawnhwei** [wmchris/DellXPS15-9550-OSX#28]
I saw your commits and realized I updated to 1.2.25 the other day but I haven't changed to aptiofix2 and I'm still using the Lilu kext. I double checked the version in bios, 1.2.25.

Everything is still working fine...

**Comment by wmchris** [comment]
Lilu is reported as non working on 10.12.5. If aptiov1 works for you, then you're one of the very few ones where the nvram is more sorted. You're lucky :-)
