### ISSUE TITLE
The Thunderbolt 3 not work? AKiTiO Node eGPU without any reaction

### ISSUE THREAD

**Issue by Jeremyye114** [wmchris/DellXPS15-9550-OSX#30]
Thunderbolt:	No hardware was found. 
but when I insert AKiTiO Node eGPU，it show“Thunderbolt:	No Diver was found”
the Thunderbolt 3 can't work？

**Comment by wmchris** [comment]
couldn't test it, because i dont own a TB3 enabled device. But i heard a lot of times it's incompatible. This is also stated in the tutorial.
