### ISSUE TITLE
how to improve the touchpad?

### ISSUE THREAD

**Issue by jianghaizhi** [wmchris/DellXPS15-9550-OSX#34]
On 10.12.5, the touchpad works not good, is there any method to improve it?

**Comment by wmchris** [comment]
you can edit the config file within the kext VoodooPS2Controller.kext. But obviously this is not a Dell XPS related issue, so its not a bug for reporting here

**Comment by jianghaizhi** [comment]
Some body report that the touchpad works better in 10.11. Maybe there is room to improve the experience of touchpad. Some people may know how to improve it and I believe it's better to have a discussion among peoples.

**Comment by wmchris** [comment]
no. same driver.

**Comment by jianghaizhi** [comment]
May be there are some body else know how to improve it. It's better to allow a discussion, so that we can work together to improve the whole tutorial and enhance the experience of 9550.

**Comment by wmchris** [comment]
as i said: edit the config. i modified it the way i like it the most. this is btw not a discussion - this is an issue reporting system. You're clearly looking for a forum like insanelymac.com.
