### ISSUE TITLE
Couldn't allocate runtime area error

### ISSUE THREAD

**Issue by th3v0ice** [wmchris/DellXPS15-9550-OSX#35]
Hi,

Thank You for all the hard work that was put into making this tutorial. 

I do, however have a problem. After following the tutorial on calculating the slide I managed to get the system to install and boot a few times. I used two different slides, 562 and 21474. Now, it wont boot at all, what ever value I put into the slider it's still giving me the same error. 

What can I do to resolve this?

Thanks.

**Comment by wmchris** [comment]
these values are way too high. either you've selected the wrong slots or your calculations were wrong.

**Comment by th3v0ice** [comment]
Then I am not really clear on how should I calculate the slide. Here is my memory map.

![memmap](https://user-images.githubusercontent.com/4531774/27273554-d94f5182-54cf-11e7-89b8-e9aae3ad7108.jpeg)

I am getting the error that I need 0x146bd pages. First available large enough number of pages is at 
 Available  0000000006B78000-0000000024606FFF 000000000001DA8F 000000000000000F, so taking the Start address of this block 0000000006B78000 and converting it into the base 10 format, deducting 100000 and dividing by 200000 I get 562, which is obviously wrong. 

I dont really get what You mean by add the number of pages until the first large enough block, then what? It not clear to me what the TARGET is? I tried adding number of pages until the first available large enough block but I cant deduct 100000 from that value neither in base 10 nor hex. What am I missing here. 

Thanks.

**Comment by wmchris** [comment]
nope, you have to calc in base 16 all the time. Then its slide = 53.

**Comment by th3v0ice** [comment]
Ah, ok. Thanks!

**Comment by wmchris** [comment]
updated the tutorial, made `use a hexadecimal calculator` more visible.

**Comment by th3v0ice** [comment]
Maybe it would be more clear if You put (TARGET - 0x100000) / 0x200000. That way there is no doubt on what to do.

**Comment by wmchris** [comment]
you cant enter 0x values in the mac calculator, which would really give problems to users who dont know what a hexadecimal number is.

people who know the hexadecimal syntax should not be confused by it as well.

**Comment by th3v0ice** [comment]
Yeah I cant agree more. I read Your tutorial but the choice of words was a little bit strange to me. You know the language barriers and stuff. I took the liberty to modify Your tutorial on this issue. Take a look at it and use it if You want. I am sorry if I offended You in any way by doing this. 

[How to calculate the slide parameter for OsxAptioFix2Drv.docx](https://github.com/wmchris/DellXPS15-9550-OSX/files/1084233/How.to.calculate.the.slide.parameter.for.OsxAptioFix2Drv.docx)

**Comment by wmchris** [comment]
all okay, was not offending to me. Just a problem in the last few days with people who dont read anything and open one ticket after another. I know the language gap, i'm not english native, too. I'll edit the tutorial with your doc and give you credits. thank you
