### ISSUE TITLE
Some times stopp at boot logo when use AppleALC

### ISSUE THREAD

**Issue by gujiangjiang** [wmchris/DellXPS15-9550-OSX#36]
Sometimes i have stoped boot at boot logo when i use AppleALC.
When i delete the AppleALC the problem have solved.

I have tried VoodooHDA and have no problem but the internal and external mic have bug and cant change internal and external speakers.

If have any other problem in AppleHDA or AppleALC?

**Comment by wmchris** [comment]
i'm using it for a few month now without a problem. can you boot in verbose mode and look up why it stops booting?

**Comment by gujiangjiang** [comment]
@wmchris 
On the system log i only find Sound Assertion error.

Many people who use AppleALC or aDummyHDA have this problem and pretty sure.

While use voodoohda have no this problem.

https://github.com/darkhandz/XPS15-9550-Sierra/commit/a8747654400cf8d50e20390cec919e04e4c01032

Many people report this problem but we dont found any problem with aDummyHDA or the AppleALC.

I have made some AppleALC for the other laptop and have no this problem but only XPS have this problem and ony in 10.12. I think the 10.11 have no this problem.So i have to wait 10.13 and want to know if 10.13 can solve this problem.

The problem with no usefull log to debug and we have no any usefull infomation to solve that.

Said.

**Comment by wmchris** [comment]
i can only suggest using syscls version of prepatched applehda. its very stable and good to use.

**Comment by gujiangjiang** [comment]
@wmchris 
I have a found with this problem.

It is related with HDMI Audio.

I have found only i put FakePCIID_Intel_HDMI_Audio.kext and FakePCIID.kext into kext folder then it will not have this problem.If i delete this 2 files the problem stll happen,

But i dont know why but it is a pograss to solve this mass prople.

Thanks.
