### ISSUE TITLE
 my XG3 drive may  has been sacrificed....

### ISSUE THREAD

**Issue by LaboratoryK** [wmchris/DellXPS15-9550-OSX#37]
> i7+1080P+Toshiba XG3 256GB
BIOS ver1.2.5
my SSD's firmware has been updated to newest in early May
Hard Disk mode set to ACHI throughout

About 3 days ago,
For convenience,I use a stick with Ubuntu 16.04 (download from Ubuntu offical website)right beside;
When running `sudo smartctl -a /dev/nvme0`
it showed me with `unable to detect device type . . . `
And I directly executed`nvme format -l 1 /dev/nvme0`
it showed `. . . fff . . .`(sorry unable to remember clearly),seemed succeed.
And then I run it for another time(2 times in all)~

Reboot to Ubuntu live,
it seemed to be success,(hadn't check carefully,at least all partitions in the disk has been erased)

But when I reboot and get into OS X (10.12.5) installation,
***(I hadn't replaced the config.plist with the 4Ke one at the first tme,
because I missed the 4kconfig.plist for 4K screen version[Wanna cry])***
I can't find the internal SSD,
Even when I have replaced the plist file later, 
even when I reboot to Ubuntu live/Windows to go,
I can never find it again.
in the Diagnostics mode in BIOS,
it shows `Hard Dirve not installed`

even pulling it out and inserting again do nothing.
even reboot over and over agagin can't help~

And I lost it since then~~~
QAQ ~~

Could you help me?
Is there anything I can do to rescue my SSD?
or only by after-sale service ?

**Comment by wmchris** [comment]
its not a common problem. you have to take a look at the NVMe namespaces. It's possible you killed them on accident. But its also possible your drive was faulty (toshiba seem very fragile lately, break down on normal usage :( )

If you have after-sale service and you're not entirely sure your drive is really defect - i would suggest trying to fix it. At least in my country the Toshiba drives will be swapped with much slower Samsung ones (2/3 - 1/2 of the speed).

**Comment by malhal** [comment]
You need to keep turning it off and on for different periods of time and eventually it'll come back. Using a NVME to USB adaptor can make this easier. Then you can apply the firmware fix:

- Fixed issue encountered in some system where drive is unable to detect after dirty power down
https://www.dell.com/support/home/en-uk/drivers/driversdetails?driverid=2n42w

**Comment by Icetard** [comment]
@malhal Thank you, dude. You are so nice, but the SSD has already been replaced with another model by Dell maintenance officer long ago.
