### ISSUE TITLE
10.12.5 Graphics Memory only 31MB

### ISSUE THREAD

**Issue by PromiseYo** [wmchris/DellXPS15-9550-OSX#38]
my laptop is i5 4k, bios version 1.2.25, i use @corenel clover config,its not for 4k,but i can install successfully and also did 4k command .  but Graphics Memory still only 31MB, and brightness cant adjust. other is ok.
 do u konw where the problem may be？ thanks sincerely！！！

**Comment by wmchris** [comment]
sorry but shouldnt you ask in corenels repo, then? ;-)
