### ISSUE TITLE
Question about CPU shift

### ISSUE THREAD

**Issue by zmm1234** [wmchris/DellXPS15-9550-OSX#39]
Does your ACPI/*.aml support CPU shift，or has other method to support this function

**Comment by wmchris** [comment]
sorry, but what is CPU shift? you mean speedstep or HWT?

**Comment by zmm1234** [comment]
@wmchris sorry，it's speed shift or HWP,  can you support this function? thinks.

**Comment by wmchris** [comment]
please inform yourself before asking such questions.
