### ISSUE TITLE
Sending jpg file over Wechat

### ISSUE THREAD

**Issue by ImmortalLeaf** [wmchris/DellXPS15-9550-OSX#4]
Hi I suppose that you do speak Chinese right?

I posted a issue of failing to send jpg files over Wechat under darkhands' tutorial [https://github.com/darkhandz/XPS15-9550-Sierra/issues/64] and I doubt that the issue was caused by either intel hack or the 4k screen patch. I wonder if you have a 4k version of xps 15 and could help me thorugh this problem. Thank you!

**Comment by wmchris** [comment]
sorry i dont speak chinese and i dont even know what wechat is.
