### ISSUE TITLE
Dodcool DC35

### ISSUE THREAD

**Issue by HeavenVolkoff** [wmchris/DellXPS15-9550-OSX#41]
Hi,
I recently bought this usb-c dongle, [Dodcool DC35](http://www.dodocool.com/usb-hubs-1771/p-dc35b.html), and it is fully functional with our laptop. I tested on 10.12.5 with your latest files, and everything worked out of the box, no driver or anything needed. The only aspect I couldn't test was the USB-C Power Delivery port, but I think it should work within our laptop USB-C charging limitations.
This could be a good addition to your tutorial appendix, as a less expensive alternative to Dell's dongle.

**Comment by wmchris** [comment]
hi, thank you very much for your information.
powerdelivery works out of the box, so i assume it will work with this addapter, too. 

There are multiple converters available right now, but i dont want to link them all in the tutorial - it's just too much work to maintain...
