### ISSUE TITLE
Can not boot ,bios version 1.2.25

### ISSUE THREAD

**Issue by skinnyshy** [wmchris/DellXPS15-9550-OSX#45]
I follow this [tutorial](https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/Additional/slide_calc.md),use `OsxAptioFix2Drv-64.efi` or `OsxAptioFix2Drv-free2000.efi` and set `slide =147` , but can not boot.
![image](https://user-images.githubusercontent.com/12553514/31232269-f689f9b8-aa1b-11e7-927d-f6d654b30504.png)

this is my memmap below.

![memmap](https://user-images.githubusercontent.com/12553514/31232503-9f12d51e-aa1c-11e7-928c-3d26ed114f17.jpg)

**Comment by skinnyshy** [comment]
[CLOVER.zip](https://github.com/wmchris/DellXPS15-9550-OSX/files/1359686/CLOVER.zip)

**Comment by krim404** [comment]
sorry i dont do personal configurations. please ask on a public forum for help.
