### ISSUE TITLE
Can not adjust brightness for 4K screen

### ISSUE THREAD

**Issue by zhaoweizhong** [wmchris/DellXPS15-9550-OSX#46]
macOS 10.12.6
I can't adjust brightness for 4K screen. How to deal with it? Thanks.

**Comment by flipphos** [comment]
I can adjust brightness on my 4K screen. We all know it reverts to full after reboot.

**Comment by zhaoweizhong** [comment]
@flipphos but I cannot even adjust brightness at any time... :(

**Comment by krim404** [comment]
see step7.

**Comment by zhaoweizhong** [comment]
@wmchris I've tried it before but it didn't work.

**Comment by krim404** [comment]
try it again with newer version
