### ISSUE TITLE
Handoff/Continuity not working properly

### ISSUE THREAD

**Issue by GameShine** [wmchris/DellXPS15-9550-OSX#48]
It seems that when testing, Continuity and Handoff do not work properly. Also, unlocking with my Apple Watch is basically out of the question. Is it possible to fix this?

**Comment by krim404** [comment]
i dont have an apple watch, so a big no on this case (unless someone donates me one ;-) )
continuity and handoff is fixable, but i didnt have the time till today to look into it.

**Comment by GameShine** [comment]
When I upgrade to the next version, I don't mind to donate mine to you. As for Continuity and handoff, the main problems are that the device takes a really long time to copy paste from the iPhone to the XPS and back. Also hotspot enabling using the XPS is really janky. These are the main problems I'm facing.

**Comment by krim404** [comment]
i just took a peek into the issue. it seems to be a problem with the bluetooth chip. i'll try something next week.

**Comment by GameShine** [comment]
Did it work, what you tried?

**Comment by krim404** [comment]
i got handoff to recognize the device and enable it in the dock, but it seems like the exchange of the actual information between the devices dont work. i'm pretty sure this has nothing to do with the bluetooth device and more with the model name truncation and/or missconfigured smbios data. This seems easily fixable.

The Continuity Activation Tool reports general functionality.

**Comment by krim404** [comment]
I applied multiple continuity patches to the current mojave build. can you please check, if these fixed your issue?

**Comment by lamhoangtung** [comment]
I have an Apple Watch Series 1 and an Airpods, after update to 10.14, everything works really great. My bluetooth, airdrop, Handoff/Continuity, unlock by apple watch, ... work instantly and very stable. Back in 10.13.6 I can't even use my airpods without lagging and random disconnection.

Great update, you nailed it @wmchris

**Comment by krim404** [comment]
Thank you for testing. I'll close this ticket then. :-)
