### ISSUE TITLE
Differences between this repository and coronel's repository

### ISSUE THREAD

**Issue by rohinrohin** [wmchris/DellXPS15-9550-OSX#50]
Hey, 
I am looking to make my first hackintosh and I was wondering what the differences between your repository and corenel's repository (https://github.com/corenel/XPS9550-macOS/) was. 

Any help on this is appreciated.

**Comment by krim404** [comment]
really cant answer it, because i dont know the other repository. its possible it contains identical files, because it looks like a personal repository for his own setup based on other repositories.

also his is set as 10.13.1, while this is for 10.13.2
