### ISSUE TITLE
After update NVME（pm981）, suffer blank screen during installation and restart

### ISSUE THREAD

**Issue by Jeremyye114** [wmchris/DellXPS15-9550-OSX#51]
I meet one problem, that's I changed new ssd (pm981, currently not start to sell yet), no matter how, I cannot install the system, when I go into the second stage of the installation, it will be restart irregularly or restart on the process of 10%. It is happening the same situation when use time machine, I feel ssd can not load suddenly! Can I use the way that FIX for the NVMe Corruption to repair？

**Comment by krim404** [comment]
its no corruption, its simply incompatible. you can try to modify the config and fiddle with the blocksize or try to install the nvmehackr kext. just take a look at the 10.12 branch.
