### ISSUE TITLE
Installation not possible: No boot entries in Clover

### ISSUE THREAD

**Issue by matthiasbayer** [wmchris/DellXPS15-9550-OSX#52]
First, thank you for putting together this extensive guide. Awesome work!

I own a Dell XPS 9550 with i7 and updated UEFI and SSD firmware (HYNIX). After creating the USB stick (UEFI), I can indeed boot from it and start clover, but there is no option to continue from this point. I can't start the installation process from there. Clover does not show any boot entries. The partition exists and contains the Install macOS High Sierra App.

I tried multiple USB sticks (64GB, 8GB), creating the stick with UniBeast and also by hand. All with the same depressing result.

**Logfile**
[Clover_Install_Log.txt](https://pastebin.com/WUsJRwb4)
[preboot.log](https://pastebin.com/rUs170iU)

**Comment by krim404** [comment]
this has nothing to do with the dell or the files, its just a bad created usb stick / bad installation source.
