### ISSUE TITLE
Attempting to update to 10.13.2 results in bootloop

### ISSUE THREAD

**Issue by deecewan** [wmchris/DellXPS15-9550-OSX#53]
When I try and install the update, I get the new Clover option 'Boot Install macOS from macOS'. When I choose this, the bootloader starts, and then dies, and I end up back at clover. If I choose 'Boot macOS from macOS' (the normal option), it goes back into the system okay, but is still at 10.13.1.

Any advice?

Edit: I've just looked through the commits and seen that I may need to update AppleALC and Lilu for 10.13.2 compatibility. Will this break compatibility with 10.13.1?

**Comment by flipphos** [comment]
It could be caused by lower version of Lilu if you use it. If it is the case, upgrading to the latest Lilu and try to upgrade 10.13.2 again.

**Comment by krim404** [comment]
it will not break 10.13.1 if you update lilu and applealc
