### ISSUE TITLE
Bluetooth works, unable to turn off.

### ISSUE THREAD

**Issue by Hammief** [wmchris/DellXPS15-9550-OSX#55]
Already googled this issue and checked the InsanelyMac forum. Unlike the other current open issue, my bluetooth does work (I use Apple's Magic Mouse to utilise all gestures), but I cannot turn it off anymore. I've tried switching back to Windows and turning it off there, but when I boot back into macOS it's on again. 

The button is 'greyed out' in System Preferences. Any suggestions how to fix?

Greetings, Hammief

**Comment by krim404** [comment]
did you find a solution to this issue?

**Comment by Hammief** [comment]
No, haven't found one. Seems like I am the only one?

**Comment by krim404** [comment]
seems like...

**Comment by xqq** [comment]
Cannot turn bluetooth off too
