### ISSUE TITLE
Question regarding 4k_sector

### ISSUE THREAD

**Issue by ggctseng** [wmchris/DellXPS15-9550-OSX#56]
I followed your directions and enabled 4k sectors:

`Supported LBA Sizes (NSID 0x1)`
`Id Fmt  Data  Metadt  Rel_Perf`
`0 -     512       0         0`
`1 +    4096       0         0 `

Does this look correct (with the active profile being the 4k sector size)?

Do I need to set the 512 sector size active?  I intend to install High Sierra.

**Comment by krim404** [comment]
high sierra dont require 4k sectors anymore, but it's still the preferred method.
so keep it that way.
