### ISSUE TITLE
when i use v3 ,but 'does printf work??'still happened

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#57]
I need to repair the brightness adjustment in my 10.13.3 version and put it in the LE folder. As a result, this problem appears, and the change of V3 is still the same.

**Comment by krim404** [comment]
https://github.com/wmchris/DellXPS15-9550-OSX/blob/10.13/10.13/CLOVER/drivers64UEFI/other/readme.md
