### ISSUE TITLE
Any solution about thunderbolt3 egpu?

### ISSUE THREAD

**Issue by hunto** [wmchris/DellXPS15-9550-OSX#58]
Recently I bought a `AORUS GTX 1080 Gaming Box`. But it doesn't compat with hackintosh(my current version is `High Sierra 10.13.3`).

### Plug it before bootup
I set `NVDisable = 0`, `use Webdriver = 1`, and it can not boot, verbose shows the loop code below:

![img_20180217_154702__01](https://user-images.githubusercontent.com/23501718/36339594-40a44420-1404-11e8-8ebf-974339799714.jpg)

### Plug after bootup
Then I tried to plug it after boot. I make the system hibernation, and plug it in, then wake up system.
It seems that device was detected, but it can not be drive correctly.(I have installed correct Webdriver and CUDA). The device shows below:

![image](https://user-images.githubusercontent.com/23501718/36339626-dd577d5a-1404-11e8-89bd-3b86886b0fea.png)

(just shows a device named `monitor`, recognized it's a nvidia card)
(and sometimes it named `nvidia chip model`)

**Comment by krim404** [comment]
sadly egpus are not supported at all. multiple persons tried to make it run, but as far as i know - without success. I leave this ticket open till someone has a solution.

**Comment by hunto** [comment]
## New update after upgrade to 10.13.4
After upgrade to 10.13.4, I can boot system when egpu was connected. And it shows below:
![image](https://user-images.githubusercontent.com/23501718/38139921-23613ffa-3464-11e8-8140-d6d22e0de930.png)

Then I installed Nvidia webdriver, boot system with options`nvidia_disable=0`, `use_webdriver=1`, but it looks the same as I installed before.
![image](https://user-images.githubusercontent.com/23501718/38139921-23613ffa-3464-11e8-8140-d6d22e0de930.png)

It's getting closer and closer, and i will keep trying. Hope someone can give me some advice to try.

And it's also loop these log below(I don't know if it's related to thunderbolt/usb-c):
```
21:56:21.859100 +0800	kernel	000998.295068 AppleUSBXHCIPCI@00000000: AppleUSBHostController::setPowerStateGated: going to state 1 returned 0xe00002e9
21:56:21.859132 +0800	kernel	000998.295109 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: attempting recovery
21:56:21.859142 +0800	kernel	000998.295120 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: 0x00000004
21:56:21.859153 +0800	kernel	000998.295128 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: attempting recovery
21:56:21.859215 +0800	kernel	000998.295192 AppleUSBXHCIPCI@00000000: AppleUSBHostController::setPowerStateGated: going to state 2 failed with 0xe00002e9
21:56:21.859225 +0800	kernel	000998.295204 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: 0x00000008
21:56:21.960158 +0800	kernel	000998.396126 AppleUSB20XHCIPort@00200000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
21:56:21.960179 +0800	kernel	000998.396150 AppleUSB20XHCIPort@00100000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
21:56:21.960191 +0800	kernel	000998.396162 AppleUSB30XHCIPort@00400000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
21:56:21.960194 +0800	kernel	000998.396165 AppleUSB30XHCIPort@00300000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
21:56:22.282321 +0800	kernel	000998.718292 AppleUSBXHCIPCI@00000000: AppleUSBHostController::setPowerStateGated: going to state 1 returned 0xe00002e9
21:56:22.282347 +0800	kernel	000998.718323 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: attempting recovery
21:56:22.282355 +0800	kernel	000998.718332 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: 0x00000004
21:56:22.282363 +0800	kernel	000998.718340 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: attempting recovery
21:56:22.282420 +0800	kernel	000998.718393 AppleUSBXHCIPCI@00000000: AppleUSBHostController::setPowerStateGated: going to state 2 failed with 0xe00002e9
21:56:22.282432 +0800	kernel	000998.718406 AppleUSBXHCIPCI@00000000: AppleUSBHostController::hardwareExceptionThreadCallGated: 0x00000008
21:56:22.383490 +0800	kernel	000998.819459 AppleUSB30XHCIPort@00400000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
21:56:22.383491 +0800	kernel	000998.819458 AppleUSB20XHCIPort@00200000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
21:56:22.383505 +0800	kernel	000998.819477 AppleUSB30XHCIPort@00300000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
21:56:22.383509 +0800	kernel	000998.819478 AppleUSB20XHCIPort@00100000: AppleUSBXHCIPort::powerOn: deadline passed (PORTSC 0x00000000)
```

my first comment in 10.13.3 it also shows these loop log and can't boot , but this time i can boot and recognize the gpu.

**Comment by krim404** [comment]
did you get hotplug to work / is hotplug even possible with a mac?
