### ISSUE TITLE
HDMI audio output and USB-DAC support?

### ISSUE THREAD

**Issue by n0k0m3** [wmchris/DellXPS15-9550-OSX#60]
I'm totally new to Hackintosh scene and really don't want to mess with config.plist using the RehabMan tutorial. Can you help me find the way to add support for HDMI audio (through direct connection on laptop and HDMI port on WD15 dock - same as the TB dock but without TB) and USB-DAC (plugged in WD15 usb 2.0 port)

**Comment by krim404** [comment]
dont have either devices, so i cant help
but it works with a lil tweaking here and there. youre already at the right location with rehabs patches
