### ISSUE TITLE
Does iMessage/FaceTime work for you guys?

### ISSUE THREAD

**Issue by solvar0719** [wmchris/DellXPS15-9550-OSX#61]
I haven't been able to log in to Messages/FaceTime lately. Whenever I attempt to log in, it simply says "An error occurred during activation. Try again". I've tried an idiot's guide to iMessage on Tonymacx86 and that didn't work. Anyone experiencing the same issue?

**Comment by krim404** [comment]
it works on any machine, but you need VALID credentials (from a defunc real mac!) it seems like you dont have them. using faked serials is prohibited and these are most likely not functional and will result in a ban of your icloud account.

What you wanna do is violating the TOS of Apple/iCloud! Installing OSX on a non apple machine is one thing, but using apple services is another.
