### ISSUE TITLE
[Question] Adaption for new XPS 15

### ISSUE THREAD

**Issue by valoricDe** [wmchris/DellXPS15-9550-OSX#62]
I'm playing with the thought of getting the new http://www.dell.com/de-de/shop/dell-notebooks/xps-15/spd/xps-15-9560-laptop/cnx95606 and using MacOS on it. Do you think it would be hard for me to adapt your setup to the following specs:
Intel® Core™ i7-7700HQ,
InfinityEdge-Display, 15,6 Zoll, FHD (1.920 x 1.080),
16 GB DDR4, 2.400 MHz,
NVIDIA® GeForce® GTX 1050 mit 4GB GDDR5
?

**Comment by ghost** [comment]
There is a forum dedicated to the 9560 here
http://www.insanelymac.com/forum/topic/324366-dell-xps-15-9560-4k-touch-1tb-ssd-32gb-ram-100-adobergb%E2%80%8B/

**Comment by krim404** [comment]
there is even a 9560 repository on github....
http://www.lmgtfy.com/?s=d&iie=1&q=dell+xps+15+9560+mac+os

**Comment by valoricDe** [comment]
😂 The big world of the world wide web makes everything possible
