### ISSUE TITLE
After update to 10.13.2, 'does printf work??' during boot

### ISSUE THREAD

**Issue by deecewan** [wmchris/DellXPS15-9550-OSX#64]
Hi,

I have tried everything I can think of/I have found in the forums about this issue and I cannot get it to boot. Every time it says `does printf work??`

I have tried
- OsxAptioDrv2
- OsxAptioDrv3
- OsxAptioDrv + Test2
- OsxAptioDrv-free2000
- AptioMemoryFix

All tried multiple times, all failed.

When I first got the system to boot, I was able to use OsxAptioDrv (as is included by default). Then, after a change, I changed to OsxAptioDrv2, but I was able to keep `slide=0`. Eventually, that stopped working and I was able to get a decent slide value ( had to use the second available block - the first one was resulted in `slide=0`, now it is `slide=168`).

I have tried everything I can think of, and now I can't get anything to boot. Not the install USB, not the install, not recovery, nothing. Any advice for this issue?

EDIT:

I have just been trying out some more things.
I can successfully avoid `does printf work??` when I try and boot to the installer using `OsxAptioFix2Drv`, but I get stuck in a loop with `BrcmPatchRAM2` constantly initialising and never actually make the install screen (waited about 15 minutes with no success). So, the installer target works from Clover, but every other target results in `does printf work??`.

**Comment by WildSpy** [comment]
Same problem

but i have that issue on install. Fix with OsxAptioDrv-free2000

**Comment by deecewan** [comment]
free2000 does not fix my issue unfortunately :(

**Comment by krim404** [comment]
There are some computers, where the memory is too fragmented. free2000 or the Memory-Fix should try to rearrange a lil bit, but if this fails there are only very few posibilities.

I dunno why, but the size of the kernel on newer OSX versions seem bigger than the memory it wants to allocate.

You can try to reduce the size of the kernel, obviously this only works, when the installation was possible. It can be very hacky, unstable and slow on boot. Try to disable kext cache as first step, this worked for other people in the past (please use google for a tutorial). But dont forget: some hacks depend on a kext cache, so this is just a first step.

Maybe there are other posibilities, but i dont have such a system, so i cant debug it.

**Comment by deecewan** [comment]
I should note that I successfully installed and the system was 'stable', but it was a new system, so I decided to upgrade to the latest version from the App Store. I installed 10.13.3 successfully and boot into it a couple of times (I needed OsxAptio2 for that). Then there was one more update, I can't remember the name, and after that it won't not get past.

I have gotten it to successfully boot one time, but after that it was back to the same issues as before.

**Comment by krim404** [comment]
multiple persons reported this after the update. only solution so far is the free2000/memory-fix OR the kernel slim down. if you find a different fix, please report it here and i'll add it to the tutorial.

**Comment by ghsssss** [comment]
Same to me！when I change the file of L/E，the error will appear！

**Comment by ghsssss** [comment]
The probability of the occurrence is so high

**Comment by ghsssss** [comment]
when i updated the 10.13.4，the error is allocation error 13ed1 on startup，but the slide always is correct，need to rebuild the kext cache，but the backlight become invalid.i am using the aptiomemory.efi.

**Comment by ghsssss** [comment]
我打中文了（不习惯英文），上述问题我通过使用aptioMemeryFix和OsxlowMemFixDrv解决！你们也可以尝试测试，之前我的禁行概率是基本上每天一次，多的时候每次禁行，只能通过重建缓存解决，现在一星期禁行就一次，而且这一次禁行以后，第二次是可以进去的！

**Comment by krim404** [comment]
with the new bios 1.8.0 and the files of mojave, it seems to fix this issue. i'll close it for now. Please reopen if this issue still exists on 10.14.
