### ISSUE TITLE
Dell adaptor DA200 Ethernet/USB not Working

### ISSUE THREAD

**Issue by cos120** [wmchris/DellXPS15-9550-OSX#65]
Hi,

My da200 adaptor HDMI works fine, but the ethernet works sometimes, I need to replug it many times until the USB lan appeared. I use DW1560 wifi card, does it affect the adaptor?

Thanks for your help!

<img width="726" alt="2018-03-27 10 16 30" src="https://user-images.githubusercontent.com/6364761/37942978-32fd1ba0-31a8-11e8-9ed5-ad7cc4d3725b.png">

**Comment by krim404** [comment]
Internal Wifi has nothing to do with USB-C. Your question already got answered in the forum thread on insanelymac, please read it there.
