### ISSUE TITLE
There is a problem with the slide value

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#68]
![img_20180403_202433](https://user-images.githubusercontent.com/25170955/38249297-cb34f89a-377d-11e8-82f3-539b0de32d92.jpg)
![Uploading IMG_20180403_202606.jpg…]()
this is 10.13.4.

**Comment by yaozaiyu** [comment]
![Uploading IMG_20180403_202606.jpg…]()

**Comment by ghsssss** [comment]
![img_20180403_202606](https://user-images.githubusercontent.com/25170955/38249526-84f5b9d6-377e-11e8-8e35-886b3ae8d45c.jpg)
