### ISSUE TITLE
USB-C not hot-pluggable?

### ISSUE THREAD

**Issue by scottsanett** [wmchris/DellXPS15-9550-OSX#7]
I've used (almost) the exact same CLOVER configuration, kexts and patches with darkhandz and I've noticed an issue with USB-C. The port can be recognized the first TWO times I plug it in but nothing happens after that. I will have to reboot the machine to make it work. I wonder if anyone else has experienced similar issues.

**Comment by wmchris** [comment]
sadly the USB controller shuts down after each time you plug/unplug something. the usb-c hotplug fix simply tries to keep the controller enabled, but this doesnt work all the time. if it's shut down no new hotplug events are triggered. :(

**Comment by wmchris** [comment]
dpassmor came up with a fix. can you check it?

**Comment by wmchris** [comment]
seems like it is fixed now.
