### ISSUE TITLE
I found a solution to the white and flicker

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#70]
https://github.com/yaozaiyu/tutorial
I hope you can test it.

**Comment by krim404** [comment]
sorry i will not test random binaries from unknown sources - too risky. also i'm not affected by the flicker.

please write in
https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-high-sierra-10131-quick-installation/

**Comment by krim404** [comment]
oh btw please can you tell us the source of the fix or did you find it yourself?

**Comment by solvar0719** [comment]
From what I gathered this solution is taken from a Chinese Hackintosh forum. I've tested it myself and I've noticed no change. But then again my monitor doesn't flicker, much like yours.

**Comment by krim404** [comment]
got report as "working". Added it to the repository, but i redownloaded all files (just to make sure). Thanks.
