### ISSUE TITLE
Unable to install the security update

### ISSUE THREAD

**Issue by solvar0719** [wmchris/DellXPS15-9550-OSX#71]
On reboot the update simply failed with a dump window and a dialog with four options. I have never seen anything like this before. Any solution for this as of now?

**Comment by ghsssss** [comment]
this is my log of fail
[安装器日志 25-Apr-2018.txt](https://github.com/wmchris/DellXPS15-9550-OSX/files/1949670/25-Apr-2018.txt)
@wmchris

**Comment by solvar0719** [comment]
The update was successful after I deleted verbstub.kext (and applealc, not sure if this is necessary) from clover.

**Comment by krim404** [comment]
These are required for sound (especially for usage of the headphone jack). removal will greatly decrease the stability of the sound output :-(

**Comment by solvar0719** [comment]
@wmchris Actually I meant deleting it only during the installation of the update lol. The system reboots twice for this security update. I put them back in after the update was complete and have no problem whatsoever.

Also I'm not so sure about why my last update was successful. The other guy above deleted them as well and he failed regardless.

**Comment by krim404** [comment]
my update was successful without deleting anything but upgrading ALC first. never tried with old one.
