### ISSUE TITLE
Solve the problem of opening 8 apples

### ISSUE THREAD

**Issue by ghsssss** [wmchris/DellXPS15-9550-OSX#72]
![87d19792-162b-4bb2-9a5d-41077bc56992](https://user-images.githubusercontent.com/25170955/39455439-f3f950be-4d12-11e8-80d7-adcb808f4c0c.png)

**Comment by krim404** [comment]
???

**Comment by ghsssss** [comment]
When Apple logo starts, there will be a flash, actually 8 apples.Some people have, some people do not
.That is to change the last second values to 64.

**Comment by krim404** [comment]
in the future, please write down the issue, the details of problem, the resolution and the source of the fix.
you meant the short flash while switching from high-res to high-dpi mode on bootup? the short flicker?

**Comment by ghsssss** [comment]
NO，I'm set the UIScale=2，the apple logo always is big.When the screen flashes, some people can see 8 rows of Apple logo, and then disappear.

**Comment by solvar0719** [comment]
@wmchris Yes that's what he meant, the flash of 8 horizontal Apple logos during that flicker. I see it as an arbitrary incidence as the appearance of it is unpredictable.
