### ISSUE TITLE
Upgraded Toshiba 512 SSD THNSN5512GPUK, but drive still not showing up in Ubuntu

### ISSUE THREAD

**Issue by Peppershaker** [wmchris/DellXPS15-9550-OSX#73]
Upgraded Toshiba SSD to latest firmware on Dell 9560. Original BIOS setting that came with the laptop. Has anyone had this problem before? Ubuntu booted from Live USB.
Edit: BIOS setting for drive is currently on RAID ON, and not AHCI

**Comment by krim404** [comment]
this is for the 9550, not the 9560.
