### ISSUE TITLE
Headset microphone not activated with ComboJack?

### ISSUE THREAD

**Issue by solvar0719** [wmchris/DellXPS15-9550-OSX#75]
I only just realized this today after all this time using it. The microphone in my headset is simply not enabled when I choose headset on plugging in. Audio output is always internal microphone. Is this expected behavior?

**Comment by krim404** [comment]
nope, this is not expected...

**Comment by solvar0719** [comment]
Has anyone else experienced this? I don't think I'm the only one. Also is there a way to debug?

**Comment by krim404** [comment]
well youre the first one who reported this issue. the "hack" is from a user on insanelymac, but he disappeared as far as i know. you can only ask there.

**Comment by michyprima** [comment]
I'm having the same issue with my 9550

**Comment by ghsssss** [comment]
me too

**Comment by krim404** [comment]
i'll close this ticket for now. Please reopen if this issue is occuring on 10.14.
