### ISSUE TITLE
10.13.4 USB Installer: "Still waiting for root device"

### ISSUE THREAD

**Issue by badstorm** [wmchris/DellXPS15-9550-OSX#76]
I used your tutorials and files and with HS <= 10.13.3 all works great. Now I tried to install HS 10.13.4 but no way to boot into the setup. I always get "Still waiting for root device". I made the usb installer as apple suggest (https://support.apple.com/en-us/HT201372) and i have the last clover version installed (with yours kext and confiugration).

Any ideas?

Thanks

**Comment by krim404** [comment]
newer installers from the app store do not contain all required files for installation. you need to get another copy of HS.
