### ISSUE TITLE
Network interface order?

### ISSUE THREAD

**Issue by shawnhwei** [wmchris/DellXPS15-9550-OSX#8]
You say for iServices to put the fake ethernet before Wi-Fi, but some iMessage setup tutorials say the primarily used interface should be on en0, which would be Wi-Fi.

Can you explain the discrepancy?

**Comment by wmchris** [comment]
not really a discrepancy - the mac address is used for security reasons. normally its from the BT device, which is missing, thats why the first lan interface is used. your smbios relies on these values, which are essential for the iServices.

if you have a spoofed network device: put them on en0, if not, use your wifi as en0 to prevent something else going there.

**Comment by shawnhwei** [comment]
I see. What is the purpose of the spoofed ethernet?

**Comment by wmchris** [comment]
to have the exact same mac adress as an active connection on en0.
