### ISSUE TITLE
apple NVMe controller kext randomly panicking on wake from sleep

### ISSUE THREAD

**Issue by michyprima** [wmchris/DellXPS15-9550-OSX#84]
My unit has a toshiba nvme ssd which I set in 4k mode. This allowed my ssd to work natively without any patches (trim works fine as well).

The only issue I have with it is that my notebook sometimes, when waking up from sleep, panics. This happens like a third of the times, the other two thirds it wakes up normally.

To be clear, this was already happening before I applied the change mentioned in #78

**Comment by krim404** [comment]
can you supply more details on the panic?

**Comment by michyprima** [comment]
sure here are the logs!
[Archivio.zip](https://github.com/wmchris/DellXPS15-9550-OSX/files/2108507/Archivio.zip)

**Comment by krim404** [comment]
did you disable hibernation in your system?
i can confirm that toshiba with 4k works well without any KP... so either its a hardware defect or something configured the wrong way.

**Comment by solvar0719** [comment]
I might have had this problem when I was on BIOS 1.7.0. I downgraded it to 1.6.0 and haven't had this problem since.

**Comment by michyprima** [comment]
@scottsanett it may be a dsdt change. Mind to share your acpi tables so I can compare to mines? Please dump em with clover.

@wmchris pmset -g:
```
MBP-di-Michele:~ michele$ pmset -g
System-wide power settings:
Currently in use:
 standbydelay         10800
 standby              0
 womp                 0
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 powernap             0
 gpuswitch            2
 networkoversleep     0
 disksleep            0
 sleep                0
 autopoweroffdelay    28800
 hibernatemode        0
 autopoweroff         0
 ttyskeepawake        1
 displaysleep         10
 lidwake              1
```

**Comment by solvar0719** [comment]
@michyprima Not at all. Do you need the patched ones or unpatched ones?

**Comment by michyprima** [comment]
@scottsanett I'd like to see the unpatched ones from 1.6.0 and compare them with mines. Press F4 on clover boot screen, you can then find them in EFI/EFI/CLOVER/ACPI/origin.  thank you!

**Comment by krim404** [comment]
i'll close this ticket for now. Please reopen if this issue is occuring on 10.14.
