### ISSUE TITLE
Bluetooth Issue - Slow Boot

### ISSUE THREAD

**Issue by stoppingtimetomakesense** [wmchris/DellXPS15-9550-OSX#87]
I'm having issues with Bluetooth where occasionally when I boot there's this hiccup during verbose: 

**kexts stall(1), (60s): 'BCM2045A0'** 

At times it'll boot without this issue with bluetooth working and times where it will boot with the issue above without bluetooth working.

Has anyone had this before?

**Comment by krim404** [comment]
can confirm, this is a common problem. sometimes even hiccups from sleep. to be honest: i didnt search for a fix, yet.

**Comment by krim404** [comment]
seems to be fixed with 10.14.
