### ISSUE TITLE
Post Installation extension/ files missing

### ISSUE THREAD

**Issue by Koerner** [wmchris/DellXPS15-9550-OSX#88]
I read the old issues and the forum, but did not find a solution for my problem:

I installed OSX according to the manual (had to change slide parameter) and now wanted to proceed with the post installation. 

But there is no `/System/Library/Extensions/AppleACPIPS2Nub.kext` neither `/System/Library/Extensions/ApplePS2Controller.kext`. What did I wrong and where can I find these files.

System: 9550, i5, 12GBRam, 60GB SSD (SATA)
OSX: 10.13.6

**Comment by ghost** [comment]
You have to be more specific about your issue. What are you trying to do. What step. If they are not there do not worry. I believe you are trying to copy something from the DellXPS9550 to your System. I didn't have those above either. You are not gonna using those files anyways

**Comment by krim404** [comment]
there is a reason why the std error is piped to null :-). These must be removed in case they're existing (for ex using this tutorial to upgrade from an older osx version)
if you dont have them: everything is fine.
