### ISSUE TITLE
couldn't allocate runtime area

### ISSUE THREAD

**Issue by kingkelo** [wmchris/DellXPS15-9550-OSX#89]
无法进入系统couldn't allocate runtime area

**Comment by ghsssss** [comment]
same as me!change some kext can be this.

**Comment by krim404** [comment]
why did you (kingkelo) reply on a completly different issue (https://github.com/wmchris/DellXPS15-9550-OSX/issues/48) before creating this one? There is a tutorial inside the repository regarding your issue! Also this has nothing to do with kexts. Please read my tutorial when using my files.

BTW: english please. Es bringt euch schließlich auch nichts, wenn ich in deutsch schreibe, oder?
