### ISSUE TITLE
slide value calculation has changed

### ISSUE THREAD

**Issue by m9tdev** [wmchris/DellXPS15-9550-OSX#92]
I think the calculation for the slide parameter has changed with new versions of Clover. After updating clover a couple of days ago, today my laptop wouldn't boot anymore and I would get the "Couldn't allocate runtime area" error. 

I've calculated a slide value for a free area of more than 0x1A000 pages at 0x13DD4000 before, which resulted in slide=159. Now if i boot I get "Error allocating 0x12122 pages at 0x19963000". Tried some random slide values and eventually it would boot at slide=109.

Seems like the calculation has changed, but a quick google search didn't result in any recent news/changes about it for me.

Edit: using the v3 fix btw and my previous slide value has worked for me for almost half a year now.

**Comment by krim404** [comment]
well for now, stick to the older version, i'll not get the time to check the clover sourcecode in the next few weeks. if anyone else wants to contribute: help wanted. :-)

**Comment by CyJaySong** [comment]
I upgraded the Clover version（ 4813）, but the previous slide still work.

**Comment by krim404** [comment]
i did a lil bit research and was unable to find any information about a change. Maybe the OP has a different problem?

**Comment by m9tdev** [comment]
I don't know either then. 

Slide 109 worked on the new version for me, but I've gone back to the version in the repo just to be sure and everything still works/boots with slide 159.

I'll just close this issue then as nobody can reproduce it and there are no issues with the old version.

**Comment by krim404** [comment]
maybe you're loading different kexts or modules, so the fragmentation on your memory changes or your kernel is bigger in size?

**Comment by m9tdev** [comment]
Nope didn't update, add or revert any kexts or modules that weren't already there
