### ISSUE TITLE
load kext then auto reboot

### ISSUE THREAD

**Issue by CyJaySong** [wmchris/DellXPS15-9550-OSX#93]
I am sorry to  bothering you again on the first day of the New Year. I recently found another problem. When my 9550 turning on, it often restarts automatically when load kext. Until Iong press the power button to force shutdown and then boot, it is possible to boot normally.

**Comment by krim404** [comment]
restarts when load text? this doesnt make sense. please take a look at your kernel crash dump, identify the culprit and open a ticket in the bugtracker of the corresponding module.

**Comment by CyJaySong** [comment]
sorry,i used wrong word. not text, is restarts when load kext.

**Comment by krim404** [comment]
still same procedure. Please take a look which kext is the culprit, check for updates, report it to the original author and report back in case it has something to do with an incompatible kext in this repository

I have multiple working enviroments, so i doubt it has something to do with the supplied kexts from this repository.
