### ISSUE TITLE
sorry,i used wrong word. not text, is restarts when load kext.

### ISSUE THREAD

**Issue by CyJaySong** [wmchris/DellXPS15-9550-OSX#94]
sorry,i used wrong word. not text, is restarts when load kext.

_Originally posted by @CyJaySong in https://github.com/wmchris/DellXPS15-9550-OSX/issues/93#issuecomment-450814763_

**Comment by CyJaySong** [comment]
Ask for your help again

**Comment by krim404** [comment]
Duplicate #93
