### ISSUE TITLE
Dell logo will be displayed twice when boot up

### ISSUE THREAD

**Issue by CyJaySong** [wmchris/DellXPS15-9550-OSX#95]
I'm curious why Dell logo will be displayed twice when boot up, so that I feel it's not fast enough. I checked the NoEarlyProgress option, but it still exists.

**Comment by krim404** [comment]
what do you mean with "twice"?

**Comment by Lockzi** [comment]
I have the same issue.

It comes up first for about 10-15s. then a quick black screen, then comes back for 10-15s then clover loads.

**Comment by m9tdev** [comment]
Same here!

**Comment by CyJaySong** [comment]
> I have the same issue.
> 
> It comes up first for about 10-15s. then a quick black screen, then comes back for 10-15s then clover loads.

yes, is this issue

**Comment by krim404** [comment]
hes, but this is pretty normal behaviour? i even have this on my MBP Retina 2012.

**Comment by Lockzi** [comment]
I don't believe I had this issue before upgrading to Mojave interestingly... Maybe something when updating clover?

This is most likely not normal behavior.

**Comment by CyJaySong** [comment]
https://github.com/xxxzc/xps15-9550-macos
but, this repository have not the issue.

**Comment by krim404** [comment]
tbh i only know macos this way. i even have this screen flicker on my MBPr. So maybe thats the reason i never tried to fix it. 

... or is it possible we're still talking about different things? I see a flicker when switching from bootup text mode to (as far as i know) gpu accelerated mode, and then another flicker when switching from lowDPI to hiDPI mode.

**Comment by Lockzi** [comment]
> tbh i only know macos this way. i even have this screen flicker on my MBPr. So maybe thats the reason i never tried to fix it.
> 
> ... or is it possible we're still talking about different things? I see a flicker when switching from bootup text mode to (as far as i know) gpu accelerated mode, and then another flicker when switching from lowDPI to hiDPI mode.


The issue happens during BIOS post i.e. before clover loads.
I've now also realized that the first time DELL logotype displays for about 10-15s where as the second time DELL logotype shows for about 30-40s before clover loads. Both logotypes are exactly the same. Best way to describe it is that it reboots after 10-15s and starts over with the same DELL logotype.
It's really strange.

**Comment by krim404** [comment]
just realized i misunderstood the ticket, thought of the apple logo, not the dell. Didn't read carefully.

thats not a reboot... this is the way the EFI's displaying the dell logo. It's the switch from EFI to Clover and Clover is still using the same image till the UI is loaded.

There is a change from 10.13 to 10.14, indeed - the clover version for early version of 10.13 was loading much faster (2-3 times). I'm sure this can be optimized by removing unused clover addons and fiddling with the configuration. For the sake of compatibility i left clover as untouched as possible.

**Comment by Lockzi** [comment]
Just tested and you are correct. Just like if you choose to boot Windows EFI rather than clover, the DELL logotype stays on with the windows spinner coming up below.

In addition, you are also correct in that it's now taking longer to boot, which is probably why we all thought it was restarting during BIOS POST.

**Comment by krim404** [comment]
soooo... no issue?

**Comment by CyJaySong** [comment]
maybe   _(:з」∠)_


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
