### ISSUE TITLE
NVMe cannot mount

### ISSUE THREAD

**Issue by General13K7** [wmchris/DellXPS15-9550-OSX#96]
Hello. After turning the power off frequently and enter to UEFI, my Toshiba NVMe dissapered. I can see it only in UEFI (only model name in info). No ,mount, no file system, nothing. i tried to mount it in Linux live, and i have this - Device not ready; aborting reset. Removing after probe failure status: -19
In windows Microsoft NVMe Express driver shows I / O hardware error.
When I installed MaсOS, I made 4k sector on it.
Can you advice something waht to do?

**Comment by krim404** [comment]
replacement. the drive is broken.
