### ISSUE TITLE
kernel panic sleep related only with USB-C adaptor Dell DA200

### ISSUE THREAD

**Issue by TiberioG** [wmchris/DellXPS15-9550-OSX#98]
Hello, 
I have experienced multiple times some reboots when I use my USB-C adaptor original Dell DA200, my computer reboots. Here is attached the report:
Does this happens also to someone else?

[Sleep Wake Failure_2019-02-01-151645_MaXPS-774.txt](https://github.com/wmchris/DellXPS15-9550-OSX/files/2827647/Sleep.Wake.Failure_2019-02-01-151645_MaXPS-774.txt)

**Comment by krim404** [comment]
darkwake is not supported at the moment...

**Comment by TiberioG** [comment]
> darkwake is not supported at the moment...

but have `darkwake=no` as boot flag, how can I completely disable it? 
thanks!

**Comment by krim404** [comment]
maybe i've interpreted the error log the wrong way. thought it was in darkwake mode. 
however, just tried sleeping with the DA200 on my machine, worked without a problem.

Sleep is sometimes a lil bit tricky, dunno why. Try to recreate the kernel kext cache, rerun the sleep configuration script from the repository and do a proper shutdown - most time this fixes the issue.

**Comment by krim404** [comment]
because no new information has been posted - i'll close this issue till i got another reply. Just assume its fixed by rerunning the sleep configuration script.
