### ISSUE TITLE
~ key not working

### ISSUE THREAD

**Issue by lamhoangtung** [wmchris/DellXPS15-9550-OSX#99]
After update new Clover and kext from your latest commit. A single problem come up with my machine.

The ~ key above the Tab key cannot work, it return this ± or this § symbol. I tried to restart, reset the keyboard layout, etc ... but it the problem still there.

Look like no keys is sticking that can cause this problems.

Anyways to solve this problem ? Thanks you

**Comment by reece394** [comment]
Have to create a custom keyboard layout if you want the keys to be correct. Use Ukelele from [here](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele) to create it. And use new from current source to save you time repopulating the fields. Has a steep learning curve but I eventually figured it out so now my keyboard is mapped correctly. After you create the keyboard bundle save it to /Library/Keyboard Layouts and select it from the keyboards settings menu. Good luck!

**Comment by krim404** [comment]
i'm using the german layout, so the supplied keymaps in the folder optional are for the german keyboard.

For english you'll have to follow reece394s steps. But before you do this, make sure your keyboard has been identified correctly - Control -> Keyboard -> Identify. Manually pick ISO or ANSI depending on your setup.

**Comment by lamhoangtung** [comment]
Quick note on how I solve this problem

I chosen the wrong keyboard. Go to Control -> Keyboard -> Identify and manually pick ISO fixed the problem for me.

Thanks @reece394 and @wmchris for the help.
